### ISSUE TITLE
Support ranking on servers

### ISSUE THREAD

**Issue by HiDzZHD** [XLabsProject/iw6x-client#101]
Hello ! I'm french so i'll try do explain my best !

So let me explain, I was trying to do the same thing as I do on Bo2, search a lobby, then type xpartygo, and when i'm in game, type spawnbot to play and rank angainst us. First problem, xpartygo didn't work when i was in the lobby, so i'v try map mp_strikezone. That've worked. Now I just type spawnbot, bot spawn but with a jugg skin and they don't move. But in private match they works perfectly. So I decide to start a private match, spawnbot and then type xblive_privatematch 0. Thy were moving but when I entenred  xblive_privatematch 0, they stop moving. 

I make this thread just to let you know what's happened and if it's possible to fix it, indeed if u want to pass time on this issue !
Thank you for your work on those type of client, that make COD PC more playable with mor fonction than the base game !

**Comment by Trypticon8** [comment]
Adding to this, maybe have 2x XP gains as the standard for those who choose to level up as most other players are likely to be using unlockall and it could make the levelling process completely unbearable for whoever decides to do that.

**Comment by bots1245** [comment]
upvoting this post  really hoping the bo2 method gets added tired of the standard 4k xp cap if you are playing squads

**Comment by LeRutY** [comment]
Please add leveling to private matches or matchmaking, having it like Plutonium, IW4X or all others would be awesome. With bots the game won´t die but without leveling it´s boring

**Comment by Snickers-Projects** [comment]
Also adding my two cents here.
Adding
```
set xblive_privatematch 0
set scr_xpscale "2"
```
to a dedicated server.cfg file creates a ranked listed server with 2x XP, but when clients connect they still need to type `xblive_privatematch 0` on their end each time they join the server for it to take affect.

Bots will still freeze in these lobbies, but it would be nice to at least have a way to create ranked multiplayer servers of some sort in the mean time if possible. Something like having the client check that the server has `xblive_privatematch` set to 0 and setting itself accordingly or something.

**Comment by LeRutY** [comment]
It´s still not possible to level up with bots

**Comment by diamante0018** [comment]
Ranked is for dedicaed servers not private match
