### ISSUE TITLE
A very long sv_hostname creates a lot of chaos

### ISSUE THREAD

**Issue by SoyRA** [XLabsProject/iw6x-client#102]
- Without spaces: It will be a single line.
- With spaces: A new line is created every X characters.

![IW6x-01](https://i.imgur.com/GMQJ2Zr.png)
![IW6x-02](https://i.imgur.com/e6aqdc3.png)
![IW6x-03](https://i.imgur.com/UGZec3k.png)

**Comment by momo5502** [comment]
Can you figure out the exact amount of characters that starts causing problems?

**Comment by SoyRA** [comment]
No, since I haven't started on it and I'm not sure I will. 😅
But these are the `sv_hostname` I tried:

```c
// Img 1
set sv_hostname "^:Hola a todos damas y caballeros, aquí ^3Soy R.A. ^:spameando..."

// Img 2
set sv_hostname "This-is-a-test-This-is-a-test-This-is-a-test-This-is-a-test-This-is-a-test-This-is-a-test-This-is-a-test-This-is-a-test-This-is-a-test-This-is-a-test-This-is-a-test-This-is-a-test-This-is-a-test-This-is-a-test-This-is-a-test"

// Img 3
set sv_hostname "^1IW6x ^2IW6x ^3IW6x ^4IW6x ^5IW6x ^6IW6x ^7IW6x ^;IW6x ^:IW6x ^1IW6x ^2IW6x ^3IW6x ^4IW6x ^5IW6x ^6IW6x ^7IW6x ^;IW6x ^:IW6x ^1IW6x ^2IW6x ^3IW6x ^4IW6x ^5IW6x ^6IW6x ^7IW6x ^;IW6x ^:IW6x ^1IW6x ^2IW6x ^3IW6x ^4IW6x ^5IW6x ^7GGWPx"
// 1 Line : set sv_hostname "^1IW6x-^2IW6x-^3IW6x-^4IW6x-^5IW6x-^6IW6x-^7IW6x-^;IW6x-^:IW6x-^1IW6x-^2IW6x-^3IW6x-^4IW6x-^5IW6x-^6IW6x-^7IW6x-^;IW6x-^:IW6x-^1IW6x-^2IW6x-^3IW6x-^4IW6x-^5IW6x-^6IW6x-^7IW6x-^;IW6x-^:IW6x-^1IW6x-^2IW6x-^3IW6x-^4IW6x-^5IW6x-^7GGWPx"
```

And I can also tell you that:
1. The `sv_hostname` can have 467 characters, if it has one more (468): the server closes.
    - But this problem happens (only) if I type `sv_hostname` in the server console.
2. The server list should be limited to 31 or 30 characters.
    - And it seems that at 41 or 42 characters the new line appears if there are spaces (assuming that `^1` (any color) is 2 characters).
      - At least in 1920x1080, I'm not sure what will happen with other resolutions.

**Comment by momo5502** [comment]
I will limit the hostname to 30 characters. We can do a full fix once we have a lua parser
