### ISSUE TITLE
Dedicated Server Port does not change

### ISSUE THREAD

**Issue by Dss0** [XLabsProject/iw6x-client#106]
When changing the port of a server via a startup parameter, the config or the console the change will show up when executing "net_port" in the console however the server will still be running on the default port and won't be reachable on the port that was set.

**Comment by momo5502** [comment]
Probably won't be done for the initial release. Not sure how easy that'll be, as socket binding likely happens before our arxan unpacking hook

**Comment by momo5502** [comment]
That's actually a feature
