### ISSUE TITLE
Release procedure

### ISSUE THREAD

**Issue by x-dev-urandom** [XLabsProject/iw6x-client#107]
In this issue we discuss the procedure for future releases of the project.

# Suggested guidelines

The following will apply to all developing staff that is involved in pushing source code to this repository directly.

- The project will follow [Semantic Versioning](https://semver.org/) and generate and use version strings based on it.
- All to be released versions will be marked in Git with an [Annotated Tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging). As opposed to lightweight tags they allow for full descriptions, metadata (author/date of tag) and signature.
- Fixes, newly added features and other mention-worthy changes shall be documented per [Keep A Changelog](https://keepachangelog.com/en/1.0.0/). This changelog will also be reused for Git tag descriptions and displaying in the updater's UI.
- We will migrate to using `develop` as our main development branch. Our current active branch `master` will be repurposed as the branch of latest (pre-)release.
- All work that needs to be done to the project shall be done on separate feature branches (e. g. `feature/<slug>`). Those need to be merged back into `develop` when ready.
  - In case they are hotfixes for released versions, they should be branched off the respective release instead and then merged back into `develop` and a new patch version release branch.
- Each release will be prepared on its own `release/<tag>` branch. We will branch off the last known good commit on `develop` that we want to include in the release and apply last-minute hot patches/fixes separately on it before release if necessary.
- Give PRs concise and changelog-worthy titles so we can credit the authors properly in the CHANGELOG by copying info directly from the PR.

# CI/GitHub Actions

Above guidelines are fitted to allow automation of a major part of the release procedure. This section will describe the automation I want to implement to go with above guidelines.

- Releases shall be drafted via a custom GitHub Workflow. This workflow creates a Pull Request  ready for final review by developing staff. Following changes will be automatically applied before creating the PR:
  - Allow specification of a new version via user input and use it to do following changes.
  - (maybe for later:) Extract changes from commit or PR list and add them to CHANGELOG.md. Possible via [generate-changelog action](https://github.com/marketplace/actions/generate-changelog).
  - (maybe for later:) Detect whether a new version should become a patch, minor or major release and automatically generate new version number based on it.
  - Move listed changes of "Unreleased" version in CHANGELOG.md into new release section. Possible via [changelog-reader-action](https://github.com/mindsers/changelog-reader-action) and/or [keep-a-changelog-new-release](https://github.com/thomaseizinger/keep-a-changelog-new-release).
  - Create a new branch `release/<version>` for the PR.
  - Generate PR with https://github.com/marketplace/actions/create-pull-request, https://github.com/thomaseizinger/create-pull-request, or similar alternative.
- Releases shall be finalized via merging above created PRs. Finalization will be automated as follows:
  - The version and release description will be extracted from the top version section in CHANGELOG.md. Possible via [changelog-reader-action](https://github.com/mindsers/changelog-reader-action).
  - An annotated, signed Git tag will automatically be generated based on above version and release description.
  - Create release via [create-release action](https://github.com/actions/create-release) or similar action.
    - Release build files and optional additional files needed by updater shall be built and then attached to the generated to generated release. Possible via [upload-release-asset](https://github.com/actions/upload-release-asset).
  - Merge `master` back into `develop` to keep all newly generated files updated there, probably via PR again.

# Questions

- Are we preparing to ship more files than just a single binary for release? In this case, pack as ZIP or upload as separate files?
- Are we preparing to ship optional content (DLC)? How to mark and separate such optional content in a machine-friendly way (updater)?
- Are we going to fully rely on the GitHub Releases API? Rate limit would be 60 requests per hour for each IP.
- Are we going to have mirrors?
- Do we create automated releases as drafts? If not, how do we ensure releases go public with all assets attached to not confuse the updater?

**Comment by iw4x-dev-urandom** [comment]
For reference, I have based a lot of the procedure on what was done on https://github.com/thomaseizinger/github-action-gitflow-release-workflow/ to automate releases, just slightly adjusted to fit some specific requirements I had for our project. I am inviting input from every maintainer here to prepare for a smooth v1.0.0.

**Comment by x-dev-urandom** [comment]
Releases will be signed off and generated via @x-ci

**Comment by avail** [comment]
>Are we going to fully rely on the GitHub Releases API? Rate limit would be 60 requests per hour for each IP.
I very much would hope not, or at least providing mirrors - I've always had horrible peering to github's servers (usually <20kb/s download when trying to download a release)

**Comment by x-dev-urandom** [comment]
> > Are we going to fully rely on the GitHub Releases API? Rate limit would be 60 requests per hour for each IP.
> 
> I very much would hope not, or at least providing mirrors - I've always had horrible peering to github's servers (usually <20kb/s download when trying to download a release)

This part was more about how we discover that a new version exists and its changelog. While GitHub also provides hosting, I didn't strictly limit myself to just using GitHub for hosting, but I was wondering whether running against GitHub's API for version discovery was a good idea.

**Comment by x-dev-urandom** [comment]
The alternative would be to generate respective metadata files and host them on some server but I think @momo5502 explicitly requested for updates to not be backed by a server we have to host.
