### ISSUE TITLE
Delayed Respawns

### ISSUE THREAD

**Issue by Trypticon8** [XLabsProject/iw6x-client#109]
In dedicated servers, seemingly at random, spawns will be delayed as if the killcam hasn't been skipped with the camera lingering over your dead body for what would normally be the duration of the cam. Haven't noticed a pattern, happened to 3 other players I encountered. [Example](https://cdn.discordapp.com/attachments/150426226983436288/769831556759289907/killcam_delay.mp4)

**Comment by halcyo-n** [comment]
+1, happened to me after you left. 
Ive had 2 "variants" of the issue happen
1: Killcam plays, if you skip, youll see your dead body and itll wait out the killcam time
2: no killcam plays, you just wait

**Comment by icy-rotten** [comment]
+1
I was in this and it happened basically on every death.

**Comment by OneFourOne** [comment]
This issue might be related to #67 since this doesn't seem to occur on all servers.

**Comment by E3VL** [comment]
> This issue might be related to #67 since this doesn't seem to occur on all servers.

it has happened in every server i have played in. Others experienced it as well

**Comment by OneFourOne** [comment]
> 
> 
> > This issue might be related to #67 since this doesn't seem to occur on all servers.
> 
> it has happened in every server i have played in. Others experienced it as well

Playing on react which had little to no lag, I and several others didn't have an issue with the respawns. If you did have this issue, chances are that server was very laggy.

**Comment by 4doorsmorehoes** [comment]
So st0rm and I look into it and seems reconnecting the server fix it.

**Comment by efinst0rm** [comment]
Issue has been found. If a players character is not set properly on spawn the game will try and wait 5 seconds before defaulting to a random skin before respawning player.

Original game code
  ```
  if ( !self HasLoadedCustomizationPlayerView( self ) )
    {
        customizationTimeout = gettime() + 5000;

        println( "Waiting for client to load viewarms " + self.name + " at time " + gettime() );

        self.waitingToSpawnAmortize = true;
        wait 0.1;

        while ( !self HasLoadedCustomizationPlayerView( self ) )
        {
            wait 0.1;

            // At this point, we'll show a default hand for this spawn
            if ( gettime() > customizationTimeout )
                break;
        }

        println( "Finished waiting for client to load viewarms " + self.name + " at time " + gettime() );

        self.waitingToSpawnAmortize = false;
    }
```
Fixed by simply returning  `self.waitingToSpawnAmortize = false;`

```
    if ( !self hasloadedcustomizationplayerview( self ) )
    {
        self.waitingToSpawnAmortize = false;
    }
```

Thanks to Fry, Level & mikz on tracking it down.
