### ISSUE TITLE
Fatal Error - Build Number 749678 - Dedicated Server

### ISSUE THREAD

**Issue by LeonLionHeart** [XLabsProject/iw6x-client#111]
[iw6x-3-20201025000608.zip](https://github.com/XLabsProject/iw6x-client/files/5435572/iw6x-3-20201025000608.zip)

<buildinfo>
	<datachangelist>749678</datachangelist>
	<exechangelist>749565</exechangelist>
	<integrationchangelist>0</integrationchangelist>
</buildinfo>

Dedicated server crashed while idling. Don't have information on how to replicate the issue, however, hope the data helps.

**Comment by momo5502** [comment]
Similar to #104. Stack trace is completely broken...

**Comment by momo5502** [comment]
This was arxan crash and has been fixed with #119
