### ISSUE TITLE
Add games_mp.log

### ISSUE THREAD

**Issue by 4doorsmorehoes** [XLabsProject/iw6x-client#112]
plz fix.

**Comment by momo5502** [comment]
Not sure if it'll make it into the initial release, but it's definitely important

**Comment by x-dev-urandom** [comment]
Kick and ban commands are seen as their own features, and those have already been implemented. As such this issue is now tracking progress on implementing writing games_mp.log only instead.

**Comment by mjkzy** [comment]
https://github.com/Joelrau/S1x-IW6x-g_log-script
alternative is to use LUA scripting and use this mod.

**Comment by diamante0018** [comment]
Implemented in https://github.com/XLabsProject/iw6x-client/blob/develop/src/client/component/logfile.cpp
