### ISSUE TITLE
>

### ISSUE THREAD

**Issue by E3VL** [XLabsProject/iw6x-client#115]
> 
> 
> > This issue might be related to #67 since this doesn't seem to occur on all servers.
> 
> it has happened in every server i have played in. Others experienced it as well

Playing on react which had little to no lag, I and several others didn't have an issue with the respawns. If you did have this issue, chances are that server was very laggy.

_Originally posted by @OneFourOne in https://github.com/XLabsProject/iw6x-client/issues/109#issuecomment-716589029_

I had this problem on react server and i have about 40 ping on that server.

**Comment by momo5502** [comment]
What a retarded issue is that? Did you just want to comment on issue #109 ?
