### ISSUE TITLE
Mouse Polling rate > 125Hz causes occasional acceleration 

### ISSUE THREAD

**Issue by iAmThatMichael** [XLabsProject/iw6x-client#117]
Video: https://streamable.com/qr3p80

Seemingly using a mouse with >125Hz polling rate causes mouse input to randomly increase unknown on what causes it, internet experienced same issue up until Advanced Warfare afterwards it was fixed.

FragsAreUs#0001 comments saying that using http://donewmouseaccel.blogspot.com/2010/03/markc-windows-7-mouse-acceleration-fix.html fixed it for them.

**Comment by avail** [comment]
That registry fix doesn't really affect anything at all on modern games.
It only replaces windows' acceleration curve to a flat one in case `SPI_SETMOUSE` is used (older games usually)
