### ISSUE TITLE
Script execution errors in launcher

### ISSUE THREAD

**Issue by lewisboi995** [XLabsProject/iw6x-client#121]
I can't get passed this screen the play and about button don't do anything.

![unknown](https://user-images.githubusercontent.com/73561911/97368474-efb02880-18a2-11eb-8e04-7181d827ab97.png)

**Comment by momo5502** [comment]
Let me rename the issue for you

**Comment by momo5502** [comment]
As a workaround for you, you can launche the game via commandline. Just do `iw6x.exe -multiplayer` for multiplayer, or `iw6x.exe -singleplayer` to bypass the launcher and start the singleplayer

**Comment by lewisboi995** [comment]
thank you

**Comment by x-dev-urandom** [comment]
@lewisboi995 Which version/build of Windows are you running exactly? If you need a way to check, you can run `winver.exe`.

**Comment by momo5502** [comment]
Tbh, not sure if I'll bother fixing it, as #5 makes this obsolete

**Comment by diamante0018** [comment]
IW6x is now launched using the xlabs launcher so this issue can now be closed as wontfix everything is controlled by the launcher.
Additionally there is probably something wrong on OP's pc that causes this? The operating system is unknown so I can only guess he was opening the exe from a now unsupported windows version?

@lewisboi995 please see https://xlabs.dev/support_iw6x_client for the updated guide on how to play iw6x
