### ISSUE TITLE
Add proper support for fovs >= 90

### ISSUE THREAD

**Issue by Canek-77** [XLabsProject/iw6x-client#153]
Version 1.0.0 RC 1

**Comment by momo5502** [comment]
Limit is 80

**Comment by Canek-77** [comment]
> Limit is 80

also does not work, 90 worked for pre release

**Comment by momo5502** [comment]
80 does work.
90 has been removed due to bug

**Comment by Canek-77** [comment]
> 80 does work.
> 90 has been removed due to being bugged

Yes, it worked now, it's strange that not the first time ...

**Comment by diamante0018** [comment]
Would love to see this feature.

**Comment by avail** [comment]
does cg_fovScale still exist? if so, one should probably allow max cg_fov to be 80 and set cg_fovScale to 1.125 instead (the engine - at least used to - handle everything differently when cg_fovScale as opposed to just cg_fov was set). cg_fov of 80 and cg_fovScale of 1.125 are equal to cg_fov 90
