### ISSUE TITLE
0x04c9647c

### ISSUE THREAD

**Issue by cue1337** [XLabsProject/iw6x-client#160]
[yes.zip](https://github.com/XLabsProject/iw6x-client/files/5483853/yes.zip)
hi got this error aand snaky snake said i should post it here 

i like chubby girls

**Comment by momo5502** [comment]
it crashes in steam. try closing steam before running the game

**Comment by momo5502** [comment]
are you running a beta steam client?

**Comment by cue1337** [comment]
solved, steam was still minimzed opened up

i still like chubby girls and momo5502 is best setup euw
