### ISSUE TITLE
more commands

### ISSUE THREAD

**Issue by Combine900** [XLabsProject/iw6x-client#162]
is it possible too "unlock" more console commands for SP?

developer_script
notarget
give xyz
ai <- example "ai ! delete" (deletes the ai what you looking at, it exists and is some debug feature)

**Comment by FragsAreUs** [comment]
they would have to be recreated like no clip and god mode

**Comment by Combine900** [comment]
> 
> 
> they would have to be recreated like no clip and god mode

hard but why not :P

**Comment by Combine900** [comment]
Any news?

**Comment by diamante0018** [comment]
These commands have been added. 
https://github.com/XLabsProject/iw6x-client/blob/develop/src/client/component/command.cpp
