### ISSUE TITLE
Use pdcurses for the dedicated servers

### ISSUE THREAD

**Issue by GEEKiDoS** [XLabsProject/iw6x-client#163]
Also larger console window size for dedicated server, the output format from status command looks broken.

**Comment by momo5502** [comment]
We will drop the console window for dedis and actually use pdcurses to draw the entire window.
I will reuse your issue to track this

**Comment by momo5502** [comment]
This will of course include your feature request and more

**Comment by GEEKiDoS** [comment]
Cool, but I actually still like the original cod style external console tbh.

**Comment by diamante0018** [comment]
I think this was address, if not please correct me.
