### ISSUE TITLE
3 Errors in a row and a failed to make new dump error

### ISSUE THREAD

**Issue by momo5502-fanboy** [XLabsProject/iw6x-client#164]
I was playing iw6x on a server called: REACtionGAMing (i do not know if I spelled the caps right) I joined it and went AFK for a little bit, then I got shot by momo (AKA snake) then got a DirectX error immediately so I launched iw6x after the DirectX error, joined back in the server and roamed around for a bit until I get a fatal error (0xc000005) so I launched iw6x. Again and entered the same server but this time ppl were there played around for a bit and what did u expect, a fatal error (0xc000005) again so I waited for a bit and launched iw6x again and played again after 5 minutes or so but in a different server I was going to stay there since snake was about to announce the first release of iw6x and I knew the lobbies would fill up fast (except I was wrong) I moved a bit from my spawn and then I got a failed to make new dump error. this might come to other players that are not me or these problems are from my iw6x client (also I am a dumbass and do not know how to upload dump  ¯\_(ツ)_/¯) EDIT: I am now getting constant fatal errors

**Comment by momo5502** [comment]
This issue is useless without the dumps

**Comment by keqing-chan** [comment]
imma be the iw4x community and say how do i dump

**Comment by momo5502** [comment]
the dumps are located in <ghosts installation dir>/minidumps
just zip them and attach them here

**Comment by ClarkGamings** [comment]
[minidumps.zip](https://github.com/XLabsProject/iw6x-client/files/5488367/minidumps.zip)

**Comment by momo5502** [comment]
> [minidumps.zip](https://github.com/XLabsProject/iw6x-client/files/5488367/minidumps.zip)

The crashes you get are related to your GPU drivers. Please update them to fix the issue.
