### ISSUE TITLE
Dedicated server incompatible with older Windows

### ISSUE THREAD

**Issue by GEEKiDoS** [XLabsProject/iw6x-client#167]
The ```GetDpiForWindow``` and the ```SetProcessDpiAwarenessContext``` does not exists before the Windows 10 1607
So the dedicated server can't run on Server with older Windows like Windows Server 2012(R2)

![QQ图片20201104193424](https://user-images.githubusercontent.com/14933408/98107285-44702680-1ed5-11eb-9b13-ca95a94eaa75.png)
![QQ图片20201104193801](https://user-images.githubusercontent.com/14933408/98107289-46d28080-1ed5-11eb-89d2-4aba3f04944a.png)

**Comment by ColerXXX** [comment]
what about win 8.1?
