### ISSUE TITLE
Crash on startup, diffrent type of crash both on mp and sp.

### ISSUE THREAD

**Issue by Tinosaurus** [XLabsProject/iw6x-client#168]
Whats happening:
Black screen on startup, SP will show the IW6X logo on the top left, and steam fps counter on top right, MP wont show even those.

What ive tried so far:
- Running iw6x as an admin and normally, both give identical results.
- Running iw6x with a shortcut that has condition -multiplayer or -singleplayer in it, same occurance.
- Running iw6x with windows 8, or windows 7 compatibility modes, wont load into the game at all.
- Running iw6x with -nosteam shortcut condition, same blackscreen occurance.

Specs (if those happen to matter for some reason);
Mobo - Asus ROG STRIX Z390-F GAMING
Graphics Card - Asus Strix GTX 970 DirectCU II OC
CPU - Intel Coffee Lake i5-9600K
RAM - Kingston 24GB (3 x 8GB) HyperX Fury, DDR4 3200MHz
OS - Windows 10 Pro Version 2004 

Ive gotten a crashdump to occur once, and not again since. ZIP including crashdump attached below.
[iw6x-2-20201104140912.zip](https://github.com/XLabsProject/iw6x-client/files/5488091/iw6x-2-20201104140912.zip)

**Comment by momo5502** [comment]
This is a crash in your GPU driver. It's likely that we can't do anything about it

**Comment by Tinosaurus** [comment]
Ill try reinstalling + updating gpu drivers again, ill get back to you.

**Comment by Tinosaurus** [comment]
Fixed by first uninstalling nvidia drivers using DDU, then installing nvidia driver version 457.09 If this happens to occur again, bug was with version 456.71 drivers.
