### ISSUE TITLE
Fatal error (0xC0000005) at 0x0E88647C

### ISSUE THREAD

**Issue by Kraaaait** [XLabsProject/iw6x-client#170]
Launcher works, happens after clicking on Multiplayer and Singleplayer

[minidumps.zip](https://github.com/XLabsProject/iw6x-client/files/5489664/minidumps.zip)

**Comment by momo5502** [comment]
you have the same issue as #160
It's related to steam. Try closing or restarting it.
Are you running a beta client?

**Comment by Kraaaait** [comment]
Steam is on stable, the issue fixed itself while steam was on

**Comment by momo5502** [comment]
Issue was apparently fixed. Seems to be steam-related
