### ISSUE TITLE
Crash on attempt to rename a soldier

### ISSUE THREAD

**Issue by Vexilions** [XLabsProject/iw6x-client#171]
I go to my create a class and there are soldiers before you create your class and I pressed RB (to rename the soldier) and the game crashed, I attempted a few times but it just kept crashing

**Comment by Vexilions** [comment]
here's the crashdumps

[minidumps.zip](https://github.com/XLabsProject/iw6x-client/files/5490869/minidumps.zip)

**Comment by Vexilions** [comment]
oh and it happened with loadout renaming so here's a minidump that I got for it as well

[minidumps.zip](https://github.com/XLabsProject/iw6x-client/files/5490886/minidumps.zip)

**Comment by momo5502** [comment]
These are several dumps mixed together. Some are GPU related. So please update your GPU drivers.
Others are related to our code. I will try to investigate that.

**Comment by momo5502** [comment]
Update your GPU drivers. The other issue is the same as #173
