### ISSUE TITLE
Crash when using game pad

### ISSUE THREAD

**Issue by loltuhan** [XLabsProject/iw6x-client#173]
[Dump.zip](https://github.com/XLabsProject/iw6x-client/files/5491008/Dump.zip)

**Comment by momo5502** [comment]
Can you please test this binary: https://ci.appveyor.com/api/buildjobs/ypll72kfgjs7vrkc/artifacts/build%2Fbin%2Fx64%2FRelease%2Fiw6x.exe
And upload the new minidumps?

**Comment by momo5502** [comment]
This is a crash in our implementation. Hard to analyze with outdated binaries.

**Comment by momo5502** [comment]
This is a crash due to a broken SteamUtils implementation on our end. I will fix the interface as soon as possible. Thank you for reporting this issue.
Crash is at this call: 0x1404D8D5F

**Comment by momo5502** [comment]
Not that some of the dumps are DirectX crashes. So please update your GPU drivers as well.

**Comment by momo5502** [comment]
Renamed and fixed the issue
