### ISSUE TITLE
I can't use SP on IW6x

### ISSUE THREAD

**Issue by XoolXecutioner34** [XLabsProject/iw6x-client#175]
I tried to play SP on IW6x but it left me only this fatal error. pls fix simply put
![Screenshot (929)](https://user-images.githubusercontent.com/74008943/98259290-8b96ff80-1f47-11eb-80df-a2c98a89fdec.png)

**Comment by momo5502** [comment]
Please upload the minidumps located in the minidumps folder in your Ghosts installation

**Comment by XoolXecutioner34** [comment]
Github doesn't take dmp, so I will have to use a file uploader for now: 
Up-down: most recent to least recent

https://ufile.io/34z9w25x 
https://ufile.io/uajr62ir
https://ufile.io/enih8eqy
https://ufile.io/z60oxzcg

**Comment by momo5502** [comment]
See #186
