### ISSUE TITLE
Voice over packs not working

### ISSUE THREAD

**Issue by 70sx** [XLabsProject/iw6x-client#179]
Hey, just wondering if there is a way to get the announcer voice overs to work. They don't seem to be working for anyone

**Comment by FragsAreUs** [comment]
they seem to be working for me I was just using them in game

**Comment by OneFourOne** [comment]
They do work fine, you probably just don't have the files for them.

**Comment by momo5502** [comment]
Looks like that's a support question that belongs in the discord
