### ISSUE TITLE
Server configs being (mostly) ignored

### ISSUE THREAD

**Issue by Trypticon8** [XLabsProject/iw6x-client#180]
Dedis seem to ignore the mode, score and time limit (along with other game settings) stored in the server.cfg file and adding "g_gametype x" in the map rotation doesn't seem to do anything. Tried it on 2 different servers, both on different machines, to the same results on the [latest version as of me posting this](https://github.com/XLabsProject/iw6x-client/commit/e21bfee12d42af195207e6a5062bd87dc661d414). [Here](https://github.com/XLabsProject/iw6x-client/files/5499163/server.txt) is my server config along with a [screenshot](https://i.imgur.com/BYcVax6.png) of what the server looks like using this config.

**Comment by momo5502** [comment]
The keyword for the map rotation is gametype, not g_gametypr

**Comment by NeXiDE** [comment]
I recently tried to change the Health from 100 to 200 but the server is not changing the values on start up. I need to change it manually for every map rotation
Here is my [server config](https://github.com/XLabsProject/iw6x-client/files/5545606/server.txt) if needed
Probably a issue with convars not getting set?

**Comment by diamante0018** [comment]
Solved by #656

**Comment by efinst0rm** [comment]
Fully fixed in #805
