### ISSUE TITLE
Not working on windows 7?

### ISSUE THREAD

**Issue by kosamja** [XLabsProject/iw6x-client#182]
In windows 7 opening iw6x.exe is showing GetDpiForWindow error. Will you make iw6x.exe to also work on windows 7?

**Comment by Jawesome99** [comment]
Windows 7 is End-of-Life and unsupported by even Microsoft, suggest you upgrade, you will jot receive any more security updates.

**Comment by momo5502** [comment]
https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962
