### ISSUE TITLE
Windows 10 error when opening multiplayer

### ISSUE THREAD

**Issue by kosamja** [XLabsProject/iw6x-client#183]
![0](https://user-images.githubusercontent.com/29978318/98362331-56fd7380-202d-11eb-8da3-12beb55569e6.png)

**Comment by momo5502** [comment]
Please upload your minidumps

**Comment by momo5502** [comment]
The DXGI adapter failed to enumerate your outputs. I suppose this is either an issue with your displays, your graphics card, or some overlay-like software interacting with IW6x

**Comment by momo5502** [comment]
This is an issue with your GPU drivers. Update them. Nothing we can fix.
