### ISSUE TITLE
Fatal error (0xC00000005) at 0x00000000000000.

### ISSUE THREAD

**Issue by NotNotJustin** [XLabsProject/iw6x-client#188]
Pretty sure the title is the error code I'm getting every time I use my MouseWheelUp or Down in Singleplayer. It causes the game to crash completely and me to lose all my progress past my autosave point. 

An image of the error:
![Fatal Error](https://user-images.githubusercontent.com/56571132/98457753-4396f900-2150-11eb-87a8-a538845807dc.png)

I don't know of any workarounds. This doesn't happen in Multiplayer at all.

**Comment by NotNotJustin** [comment]
I just switched to Dev Build and it works flawlessly. There's a workaround for you all.

**Comment by momo5502** [comment]
See #187
