### ISSUE TITLE
Fatal error crash

### ISSUE THREAD

**Issue by leaf1074** [XLabsProject/iw6x-client#189]
Fatal error crash when trying to join a server, start a private-match, extinction & campaign.

![unknown](https://user-images.githubusercontent.com/74154006/98482570-9c26ce80-2202-11eb-8c65-9998116dfe88.png)

[minidumps.zip](https://github.com/XLabsProject/iw6x-client/files/5507043/minidumps.zip)

**Comment by momo5502** [comment]
Could be a graphics card issue or invalid game files. Where dod you get your gamefiles from?

**Comment by leaf1074** [comment]
> Could be a graphics card issue or invalid game files. Where dod you get your gamefiles from?

![image](https://user-images.githubusercontent.com/74154006/98937289-7b05fc80-24e6-11eb-93fd-9f784c7288f6.png)
![image](https://user-images.githubusercontent.com/74154006/98937376-9a048e80-24e6-11eb-9d08-aedaff5b4797.png)

also tried the dev build with no success.

**Comment by momo5502** [comment]
Can you please try to update your graphics card drivers?
I'll try to debug it later that day, and get back to you

**Comment by leaf1074** [comment]
Updating the raphics card drivers actually solved it!
