### ISSUE TITLE
FATAL ERROR CODE

### ISSUE THREAD

**Issue by SIXHS** [XLabsProject/iw6x-client#191]
FATAL ERROR  (0xC0000005) at 0x00000001405E5483 

Right when i click on multiplayer 
![image](https://user-images.githubusercontent.com/74165330/98496757-58d35c80-2210-11eb-8fc0-08f4a0248c6e.png)

**Comment by momo5502** [comment]
Please upload the minidump.

**Comment by zLowky** [comment]
Found a solution yet?

**Comment by momo5502** [comment]
We need a minidump... This issue is useless without the dump.

**Comment by momo5502** [comment]
I checked the address. This is an issue with rendering. Please update all your drivers and install all pending updates. This should fix the issue. If not, remove all software that renders overlays ontop of the game.
