### ISSUE TITLE
GetDpiForWindow DLL USER32.DLL Error

### ISSUE THREAD

**Issue by ImAstolfo** [XLabsProject/iw6x-client#194]
![image](https://user-images.githubusercontent.com/74242949/98665955-08194c00-2355-11eb-81a2-bd85b4291ad3.png)

**Comment by momo5502** [comment]
Duplicate. See #167

**Comment by momo5502** [comment]
Also, same #182.

No windows 7 support: 
https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962
