### ISSUE TITLE
About 20 mini dumbs from fatal errors

### ISSUE THREAD

**Issue by grizzzy** [XLabsProject/iw6x-client#195]
title
[minidumps.zip](https://github.com/XLabsProject/iw6x-client/files/5517359/minidumps.zip)

**Comment by momo5502** [comment]
mini dumbs. that one's new to me 😂

**Comment by grizzzy** [comment]
> mini dumbs. that one's new to me 😂

 haha woops, dumps*

**Comment by momo5502** [comment]
I have only checked 3 of the 20 dumps, but they all crash at the memmove at 0x14064B966.
Need to investigate why it crashes there and what is actually done in this function

**Comment by momo5502** [comment]
Seems that it's zlib relted. Could be that your gamefiles are broken

**Comment by momo5502** [comment]
This issue because of broken game files. Please get original cod ghost files.
