### ISSUE TITLE
Make IW6x have its own folder

### ISSUE THREAD

**Issue by SoyRA** [XLabsProject/iw6x-client#2]
Currently IW6x generates these files in the game folder:
```
__iw6x (hidden file)
arxan\*
main\recipes\*
main\save\*
players2\*
```
\
\
I propose that IW6x should continue to be installed where the game is, but that everything it generates should be stored in its own folder:
```
iw6x.exe
IW6x\__iw6x (well, this one doesn't matter because it's deleted if the game was closed correctly)
IW6x\arxan\*
IW6x\main\*
IW6x\players2\*
```
\
\
Something like FiveM, Plutonium, etc. but not so separate.
You could even make that, if you install the DLCs on `IW6x\*` (or `IW6x\DLC\*`), you will be able to use them without problems.

**Comment by momo5502** [comment]
Yep, great idea

**Comment by mjkzy** [comment]
solved?

**Comment by diamante0018** [comment]
Sounds like this was implemented but issue was not closed
