### ISSUE TITLE
Stuck on map loading

### ISSUE THREAD

**Issue by cptmacp** [XLabsProject/iw6x-client#202]
Issue : stuck on map loading , tried on private lobby and public servers 

![image](https://user-images.githubusercontent.com/11556463/99075659-dcf65d00-25df-11eb-8ffa-0af3219ecb9e.png)

weirdly it gets stuck at this number (021530) always 

loading bar does not move up even for SP 

![image](https://user-images.githubusercontent.com/11556463/99075674-e41d6b00-25df-11eb-956e-500109cfc8e6.png)

I have an original steam copy and I ran a private match from steam app  and it loads up into the match just fine 

ref :  https://github.com/XLabsProject/iw6x-client/issues/40

edit : 

extinction seem to load and can see the loading bar ( above the tips text)

**Comment by momo5502** [comment]
Can you try to update you graphics card drivers?

**Comment by cptmacp** [comment]
> Can you try to update you graphics card drivers?

I did that earlier, clean installed driver.

but if it was a driver issue, the original steam game should not be able to load the private match, BUT it works just fine there

**Comment by momo5502** [comment]
Can you create a process dump when this happens?
See this on how to do it: https://support.kaspersky.com/common/diagnostics/12401

**Comment by gaurac** [comment]
This is not by graphic some files missing but I don't know can anyone tell

**Comment by momo5502** [comment]
> This is not by graphic some files missing but I don't know can anyone tell

Your issue is related to broken gamefiles. This has nothing to do with this issue...

**Comment by gaurac** [comment]
i have download full game from this website but it not work but when i download config file from internet it starts  but it not loading maps neither singleplayer nor multiplayer .something is missing

**Comment by cptmacp** [comment]
> Can you create a process dump when this happens?
> See this on how to do it: https://support.kaspersky.com/common/diagnostics/12401

here 
dump for MP: https://drive.google.com/file/d/18E2nAD2FkAiZ1UAptWLcaqNvLkuaz15M/view?usp=sharing
dump for SP: https://drive.google.com/file/d/1A5PatAHDn_aNt4r_QuAwOWBiUsIVetYK/view?usp=sharing

( since it happens on SP also, cant load the campaign )

**Comment by gaurac** [comment]
where to put this dump file, you sure this will work. pls reply

**Comment by gaurac** [comment]
this not working pls help with other solution.

**Comment by momo5502** [comment]
Steam blocks the rendering. It seems to be a bug in steam. To fix this, you can turn off steam.

In the future, you will be able to start IW6x with the -no-steam option, this will disable our steam integration and this should fix the issue.
I haven't investigated why exactly steam freezes, but I don't think it is worth the time, as it's not an issue on our end.
