### ISSUE TITLE
RCON Server Crash When At Around 11 Players

### ISSUE THREAD

**Issue by QuadraticFormulo** [XLabsProject/iw6x-client#204]
Apparently it has something to do with the status code being too long.

**Comment by OneFourOne** [comment]
If it crashes upload the mini dump.

**Comment by momo5502** [comment]
This issue will be closed in 7 days if no info is provided

**Comment by QuadraticFormulo** [comment]
Can't get a minidump to generate: maybe because it doesn't give me any type of error but instead the window just disappears.

Pretty easy to repeat the error on your end; you can use either iw4m or multircon to test it out. 
1. Spawn 11 bots
2. either pass the status command to multircon or connect iw4m admin to the server, and wham bam, _poof_ 

you can also connect iw4m admin ahead of time and then spawn the bots. I think 11 is the magic number for a crash when sending the status command.
