### ISSUE TITLE
Game stuck on black screen when launching and says not responding

### ISSUE THREAD

**Issue by grizzzy** [XLabsProject/iw6x-client#206]
![Screenshot 2020-11-15 140910](https://user-images.githubusercontent.com/46548298/99198258-590db380-274c-11eb-8787-ce906cf69b1e.png)
I've tried updating gpu drivers, reinstalling the torrent (twice), messing with compatibility settings in properties, running as admin, adding the whole folder as an exception on my anti virus which isn't even on. The issue started happening after I reset my drives and reinstalled windows. Seems I've tried everything so please help lol

**Comment by cptmacp** [comment]
nature of the problem seems to be unknown.

**Comment by momo5502** [comment]
can you create a process dump please?
https://support.kaspersky.com/common/diagnostics/12401

**Comment by momo5502** [comment]
Pretty sure this is a driver issue

**Comment by momo5502** [comment]
This issue will be closed in 7 days if no info is provided

**Comment by gaurac** [comment]
Config.cg mossing

**Comment by momo5502** [comment]
> Config.cg mossing

Your issue is related to broken gamefiles. This has nothing to do with this issue...

**Comment by gaurac** [comment]
Create a folder name players2 and this is a solution.

**Comment by momo5502** [comment]
> Create a folder name players2 and this is a solution.

I told you to stop commenting on other's issues that are not related to your problem. I'm going to block you from our GitHub repos...

**Comment by momo5502** [comment]
I will close the issue now. You can still reopen it, if you think it's still relevant.
