### ISSUE TITLE
Character Visual Appearance Resets Upon Map Change

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [XLabsProject/iw6x-client#207]
Basically, regardless of what your squad member outfit is set to, it seems to reset everything to the first item in each list in the menus for customisation.
The only thing unaffected is the voice of the character. It remains what you set the gender to.
the appearance becomes this no matter what: 
![image](https://user-images.githubusercontent.com/33284629/99198846-17ecc200-2793-11eb-9671-deac12c7f779.png)
Loadouts and other squad member things are unaffected, only appearance.

**Comment by CosmicDreamsOfCode** [comment]
I have a theory as to why it breaks,
Normally the game returns to the menus between watches but IW6X goes straight into the next match. 
Considering leaving and rejoining the server corrects the appearance, it's probably likely that the next match instantly starting is what's to blame.

**Comment by momo5502** [comment]
Stats are not yet working. Might be related to that.

**Comment by CosmicDreamsOfCode** [comment]
It's definitely something to do with not going back to the menus. I'm not entirely sure what sort of things get set or whatever when you do but it definitely seems like something does.
I suppose stats could potentially be a reason, but I'm not entirely sure how related they could be...

**Comment by efinst0rm** [comment]
This has something to do with this 

https://github.com/XLabsProject/iw6x-client/issues/109#issuecomment-1283451294

**Comment by CosmicDreamsOfCode** [comment]
> This has something to do with this
> 
> [#109 (comment)](https://github.com/XLabsProject/iw6x-client/issues/109#issuecomment-1283451294)

I think I remember trying again after this was merged and it wasn't fixed but I don't entirely remember 
It's possible it wasn't in the version I tried
