### ISSUE TITLE
fatal error about graphics card and OS updates

### ISSUE THREAD

**Issue by cveres43** [XLabsProject/iw6x-client#209]
everytime i play a couple matches. my game crashes and tells me to update graphics card and OS. Heres my crash dump -> https://drive.google.com/file/d/1VCHCi9CMo3NDwZgafYZUTyYx1WCLD5ze/view?usp=sharing

**Comment by momo5502** [comment]
Access is blocked for me. I sent you an access request

**Comment by momo5502** [comment]
naming the dump .txt destroys it as gdrive adjusts the line endings. Your dump is broken because you renamed it. Please upload a one with the .dmp ending.

**Comment by momo5502** [comment]
This issue will be closed in 7 days if no info is provided

**Comment by momo5502** [comment]
I will close the issue now. You can still reopen it, if you think it's still relevant.
