### ISSUE TITLE
MINIDUMPS 

### ISSUE THREAD

**Issue by Brostosj** [XLabsProject/iw6x-client#210]
https://drive.google.com/drive/folders/1XqaMMkb7md6DyIqNCw5THqzVj0WKtmbQ?usp=sharing
WHEN DONE WITH IT REPLY ANYTHING

**Comment by momo5502** [comment]
YOU DON'T HAVE TO WRITE ALL CAPS.
We can also read normal text.

**Comment by momo5502** [comment]
All 3 dumps are arxan related

**Comment by Brostosj** [comment]
ok

**Comment by momo5502** [comment]
Has been fixed with #119
