### ISSUE TITLE
Fatal error (0xC0000005) at 0x0000000140167D8A

### ISSUE THREAD

**Issue by bluejeans117** [XLabsProject/iw6x-client#211]
Happens whenever I try to join any public server in multiplayer

![image](https://user-images.githubusercontent.com/45818225/99896940-3125cf00-2cbb-11eb-884e-9d26e2895f07.png)

This is the minidump here.
[iw6x-2-20201122120045.zip](https://github.com/XLabsProject/iw6x-client/files/5579076/iw6x-2-20201122120045.zip)

**Comment by momo-fanboy** [comment]
the issue is known and the staff team are figuring out how to fix the issue

**Comment by bluejeans117** [comment]
This is from the non-steam torrent version, with the DLCs downloaded. I seem to be able to play single player without any issues.

**Comment by bluejeans117** [comment]
> the issue is known and the staff team are figuring out how to fix the issue

Oh alright, then should I close it?

**Comment by momo-fanboy** [comment]
yeah, the issue has been reported many times and sending the dmp file will help the staff team fix the problem

**Comment by bluejeans117** [comment]
> yeah, the issue has been reported many times and sending the dmp file will help the staff team fix the problem

Yeah I've attached the dump file in the OP. I'll keep it open and wait for the dev to close it themselves after they check out the minidump :) Thanks for the help!

**Comment by momo5502** [comment]
This is an issue with your graphics card drivers. You are also running an outdated version of IW6x. Please update everything and tell us if that helped
