### ISSUE TITLE
Theater

### ISSUE THREAD

**Issue by alienxo** [XLabsProject/iw6x-client#212]
Theater with dollycam, greenscreen and depthmap like in iw4x and some other clients would be cool to see, editors have wanted good ghosts theater for years.

**Comment by mikzyy** [comment]
Related to this, i'm not expecting a yes but just wondering with the possibilities related to this. Couls you record every game you go when into, even if it's a dedicated server, and rewatch in theater?

**Comment by momo5502** [comment]
> Related to this, i'm not expecting a yes but just wondering with the possibilities related to this. Could you record every game you go when into, even if it's a dedicated server, and rewatch in theater? Would be cool to go stuff like frags from a server, out of theater.

Yes, that's the point of a theater mode

**Comment by mikzyy** [comment]
> > Related to this, i'm not expecting a yes but just wondering with the possibilities related to this. Could you record every game you go when into, even if it's a dedicated server, and rewatch in theater? Would be cool to go stuff like frags from a server, out of theater.
> 
> Yes, that's the point of a theater mode

thought it usually only worked for offline games, my bad

**Comment by diamante0018** [comment]
not planned
