### ISSUE TITLE
Fatal error (0xC0000005) at 0x000000014073056E. Updating Graphics and OS Updates

### ISSUE THREAD

**Issue by ECicek33** [XLabsProject/iw6x-client#213]
After I play few games I get this Error, I have updated all my Drivers & OS System and still get it. 

https://drive.google.com/file/d/1eJ8AHK_rfKZMIqUMcdlmra7OP6NEht9r/view?usp=sharing

**Comment by ECicek33** [comment]
![Screenshot (500)](https://user-images.githubusercontent.com/47883742/99989131-8ee91280-2db2-11eb-9c01-83dfab5d7994.png)

**Comment by ECicek33** [comment]
![Screenshot (505)](https://user-images.githubusercontent.com/47883742/99989183-9b6d6b00-2db2-11eb-9fbc-7f83bd7a86d8.png)

**Comment by momo-fanboy** [comment]
The staff team are working for a fix behind the fatal error issue

**Comment by momo5502** [comment]
This is a zlib decompression error. It is highly likely that some of your gamefiles are broken.

**Comment by momo5502** [comment]
Try getting the original gamefiles

**Comment by ECicek33** [comment]
> Try getting the original gamefiles

Got them all from this Github

**Comment by FragsAreUs** [comment]
> > Try getting the original gamefiles
> 
> Got them all from this Github

he is talking about your cod ghost files not the files for iw6x

**Comment by momo5502** [comment]
Yeah, I'm talking about the Call of Duty Ghosts files, not IW6x
