### ISSUE TITLE
Status missing OOB header when server is not running.

### ISSUE THREAD

**Issue by xerxes-at** [XLabsProject/iw6x-client#216]
Status response is missing the OOB header when the server is not running.
I noticed this by iw4m sending `status` via rcon while the server was loading the next map.
The server returned ` ^1Server is not running` while it should send back `\0xFF\0xFF\0xFF\0xFFprint\n^1Server is not running`

```
[2020-11-26 04:52:39.024 138.201.26.173:27022 WRN] Invalid response header from server. Expected ÿÿÿÿprint
, but got  ^1Server is not running
```

**Comment by diamante0018** [comment]
@xerxes-at I would like an update on this issue.
Does this still happen?
Thanks.

**Comment by diamante0018** [comment]
The status header is not missing.
Confirmed today.
`b'\xff\xff\xff\xffprint\n Server is not running\n'`
It's not an issue with the client.
