### ISSUE TITLE
Read error of file common_bots_mp (0x00000006) ??

### ISSUE THREAD

**Issue by davismatcs** [XLabsProject/iw6x-client#217]
I get that error and other errors like this one almost every time i try to join a game, i own ghosts on steam and i have uninstalled and redownloaded and i have verified my files on steam. 
![Screenshot (5)](https://user-images.githubusercontent.com/75097545/100392433-28573500-2ffc-11eb-8fa1-2a18b825d21d.png)

**Comment by davismatcs** [comment]
[iw6x-2-20201126150013.zip](https://github.com/XLabsProject/iw6x-client/files/5605062/iw6x-2-20201126150013.zip)

**Comment by momo5502** [comment]
> [iw6x-2-20201126150013.zip](https://github.com/XLabsProject/iw6x-client/files/5605062/iw6x-2-20201126150013.zip)
> 
> the dump file

This dump seems unrelated and is related to an issue in your graphics card driver. Please update your drivers to fix that issue.

**Comment by momo5502** [comment]
I will investigate the `read error of file` issue. It seems to be related to an invalid file handle.

**Comment by davismatcs** [comment]
i finally figured our how to update my graphics driver on my laptop, i still get read error of files, so update me if theres anything i can try to fix it. thank you

**Comment by momo5502** [comment]
Can you please upload the file common_bots_mp.ff?

**Comment by davismatcs** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/75097545/100492922-258d3a80-30f7-11eb-8148-fbaff2c423fd.png)
new error i got, idk if its useful at all

**Comment by davismatcs** [comment]
[common_bots_mp.zip](https://github.com/XLabsProject/iw6x-client/files/5610003/common_bots_mp.zip)

**Comment by diamante0018** [comment]
I think because this hasn't happened recently it was fixed.
