### ISSUE TITLE
Error Fatal

### ISSUE THREAD

**Issue by kuriipa** [XLabsProject/iw6x-client#218]
I Have a Error Fatal Menu_Content_Not_Available
![Captura](https://user-images.githubusercontent.com/75102857/100401397-f86d5900-301e-11eb-97fa-eb64704b9843.PNG)
![asd](https://user-images.githubusercontent.com/75102857/100401404-facfb300-301e-11eb-85e8-414fb368d122.PNG)

**Comment by OneFourOne** [comment]
This is caused by not having the DLC files. This is not an issue with the client. Also, if you don't already have clean game files, please get them or verify them.

**Comment by momo5502** [comment]
The first message clearly says that your cod ghost files are the issue
