### ISSUE TITLE
Dedicated Server Crash every 24 hours with Fatal error (0xC00000005) at 0x00000001E3A2A0.

### ISSUE THREAD

**Issue by FritasTechTips** [XLabsProject/iw6x-client#222]
As discussion on #vip channel
https://discordapp.com/channels/219514629703860235/265852764238774273/782505511173488682
Dump 
https://cdn.discordapp.com/attachments/265852764238774273/782537663789006848/iw6x-3-20201129042241.zip

**Comment by momo5502** [comment]
Seems to be fixed
