### ISSUE TITLE
Crashing when launching both mp + sp

### ISSUE THREAD

**Issue by z0mbieslayer** [XLabsProject/iw6x-client#231]
Here's my minidump. Not much to say other than I was playing the campaign then my entire game crashed on the second mission. 
[iw6x-2-20201130212657.zip](https://github.com/XLabsProject/iw6x-client/files/5639987/iw6x-2-20201130212657.zip)

**Comment by momo5502** [comment]
> I was playing the campaign

Just fyi, you uploaded an MP minidump, not SP.
Please always upload all minidumps, as the crashes are not necessarily caused by the same issue, especially SP and MP crashes probably have different causes

**Comment by momo5502** [comment]
However, this crash is related to steam. It's a bug in the steamclient. Either kill steam or grab a develop build and use the -no-steam parameter
