### ISSUE TITLE
SetThreadDescription not available on older Windows versions

### ISSUE THREAD

**Issue by momo5502** [XLabsProject/iw6x-client#237]
![image](https://user-images.githubusercontent.com/4027748/101496800-7e1bcd80-396a-11eb-964f-8d1b3ccb8918.png)

**Comment by clx127** [comment]
Just like im getting this error. My windows 8.1 64bit latest version

**Comment by momo5502** [comment]
This has been fixed. No need to comment on closed issues....

**Comment by clx127** [comment]
> This has been fixed. No need to comment on closed issues....

Ok, so where i can download fixed version? Could you pls give a link)
