### ISSUE TITLE
My game wont respond when i try to open it 

### ISSUE THREAD

**Issue by DragonRuler** [XLabsProject/iw6x-client#238]
https://drive.google.com/file/d/1qjzXihlIPKNWPHBJmLIpirBsH7h1Opny/view?usp=sharing

**Comment by momo5502** [comment]
Sent an access request

**Comment by DragonRuler** [comment]
> Sent an access request

i accidentally forgot to make the link a public one i changed it now

**Comment by momo5502** [comment]
Did it create minidumps?

**Comment by DragonRuler** [comment]
i dont have any minidumps

**Comment by DragonRuler** [comment]
> Did it create minidumps?

no

**Comment by momo5502** [comment]
Why was this closed?

**Comment by DragonRuler** [comment]
> Why was this closed?

i was told that if there wasn't a mini dump there's not a problem or something along the lines of that so I just closed it
