### ISSUE TITLE
i try launching my game but there is only a black screen and after a second it stops responding 

### ISSUE THREAD

**Issue by DragonRuler** [XLabsProject/iw6x-client#240]
https://drive.google.com/file/d/1UdA6IW-AqLkt2yfsC9dRkMR9JbwYIYtS/view?usp=sharing

**Comment by IMMORTALVASILIY** [comment]
It sucks, it happens to a lot of people

**Comment by diamante0018** [comment]
The download link expired and the issue is too old to reflect the current state of iw6x.
