### ISSUE TITLE
Issue joining with tester build

### ISSUE THREAD

**Issue by OneFourOne** [XLabsProject/iw6x-client#244]
When using the tester build and trying to join a server you get this: https://i.imgur.com/HOLd1aY.png

Otherwise when using the normal release build, it works fine.

**Comment by momo5502** [comment]
It seems like this commit is the issue: https://github.com/XLabsProject/iw6x-client/commit/249c33d1a131d85c494d59cd9b24331057d4d374

**Comment by momo5502** [comment]
This is related to the servers not being uptodate.
