### ISSUE TITLE
Calling a method on wrong entity type crashes the game

### ISSUE THREAD

**Issue by GEEKiDoS** [XLabsProject/iw6x-client#251]
~~Call it once is okay but no effect, call it multiple times will crashes the game.~~
~~I guess it's not the only function behave like this~~

edit:
It's my fault, it is only for player entity not for others, but it should raise a script execution error rather than crashes the game

**Comment by momo5502** [comment]
Can you verify if it's fixed please?

**Comment by momo5502** [comment]
It turns out that both players and vehicles have class 0. Meaning the class check in setOrigin succeeds for vehicles and thus setOrigin is being executed, trying to act on the vehicle as if it was a player then crashes.

**Comment by momo5502** [comment]
There is nothing we can to execpt isolating the call using SEH for such cases, but that might be alright.

**Comment by momo5502** [comment]
SEH is now active: 5ff6d31fa09ac7b05b2598d1d837430e7fc96381
