### ISSUE TITLE
Missing lua librarys

### ISSUE THREAD

**Issue by GEEKiDoS** [XLabsProject/iw6x-client#256]
![image](https://user-images.githubusercontent.com/14933408/102309539-ebc68b80-3f60-11eb-90b4-63b83aa19c9c.png)

Following 4 integrated libraries a missing
```
coroutine
table
utf8
debug
```

Especially the ```table``` lib, pretty important one

**Comment by momo5502** [comment]
coroutine is probably a no, you have timers for threadsafe delaying.
Game doesn't support utf8.
You already added table. Debug might be helpful, I agree

**Comment by GEEKiDoS** [comment]
> coroutine is probably a no, you have timers for threadsafe delaying.
> Game doesn't support utf8.
> You already added table. Debug might be helpful, I agree

The game is actually utf8, but the font does not supports it

**Comment by momo5502** [comment]
> > coroutine is probably a no, you have timers for threadsafe delaying.
> > Game doesn't support utf8.
> > You already added table. Debug might be helpful, I agree
> 
> Agreed, so I only added the table
> 
> The game is actually supports utf8, but the font does not supports it

Looked it up, you are right. UTF-8 support is sparse in the rendering engine, but it's there
