### ISSUE TITLE
Implementation json library for Lua

### ISSUE THREAD

**Issue by DoktorSAS** [XLabsProject/iw6x-client#258]
It would be very interesting to be able to implement a json library to be able to use json format files to save particular data. The json files are very easy to use and are very convenient for real-time data editing without restarting the server or script. 
Example of use
- Save custom rank such as donor rank
- Save map changes, save objects to be added or removed in a map
- Change information in real time without restarting the server or the script

I hope I've made my point. I think it is a very convenient library for future scripts.

**Comment by momo5502** [comment]
This library works and should be enough for all scripting needs: https://github.com/rxi/json.lua
