### ISSUE TITLE
cg_draw2d 0 not working,problems with unlocking the fps

### ISSUE THREAD

**Issue by XJonaSX33** [XLabsProject/iw6x-client#260]
hello, i played iw6x for some time and it was awesome but i wanted to completely turn off the in-game hud but typing in cg_draw2d 0 into the console it didnt change anything it was still set to 1, how do i set it to 0? and also how do i unlock the fps properly? because if i just type in com_maxfps 150 it unlocks the fps but the mouse sensivity randomly spikes up

**Comment by momo5502** [comment]
cg_draw2d is cheat protected. You need to set sv_cheats 1. Mouse spikes are probably because your polling rate is > 125hz. See #117
