### ISSUE TITLE
Minidump error (Multiplayer)

### ISSUE THREAD

**Issue by Farbersaw** [XLabsProject/iw6x-client#262]
![minidump eror](https://user-images.githubusercontent.com/76242135/102683838-95d42c80-4188-11eb-80b5-828ae419f866.jpg)

No matter whether its online or offline , i cannot join any game at all , sometimes it crashes entirely i cannot find from where the issue is coming from (all my drivers and systems are up-to-date btw)

**Comment by GEEKiDoS** [comment]
I think I might fixed that, see #261

**Comment by Farbersaw** [comment]
Well i donno , maybe i have to re-download the entire thing , game ran fine a week ago , now i open it and try to play it constantly crashes so i guess I'll go back to Plutonium for now until we find a fix

**Comment by Farbersaw** [comment]
> I think I might fixed that, see #261
Heres the error files 
[iw6x-crash-2-2020-12-19-13-30-14.zip](https://github.com/XLabsProject/iw6x-client/files/5719057/iw6x-crash-2-2020-12-19-13-30-14.zip) @GEEKiDoS

**Comment by GEEKiDoS** [comment]
> > I think I might fixed that, see #261
> > Heres the error files
> > [iw6x-crash-2-2020-12-19-13-30-14.zip](https://github.com/XLabsProject/iw6x-client/files/5719057/iw6x-crash-2-2020-12-19-13-30-14.zip) @GEEKiDoS

May you try this build? 
[Release.zip](https://github.com/XLabsProject/iw6x-client/files/5719061/Release.zip)

**Comment by momo5502** [comment]
#261 really fixed this issue, but unless you are a developer, tester or scripter, you are not supposed to use the develop builds. Get the official stable builds instead!

**Comment by Farbersaw** [comment]
@GEEKiDoS alright it works now , I'll update this thread in one day if i find any other issues

**Comment by Farbersaw** [comment]
@momo5502 i am using the stable build Thats what bugged me

**Comment by momo5502** [comment]
> @momo5502 i am using the stable build Thats what bugged me

No you are not. I can see it in your screenshot...

**Comment by momo5502** [comment]
> @GEEKiDoS alright it works now , I'll update this thread in one day if i find any other issues

No, please do not update this issue. Each individual problem belongs in a separate issue. So create new issues for each problem you get.

**Comment by Farbersaw** [comment]
@momo5502 my bad it was the dev build (i have both cuz I'm modding cod ghost like crazy )
