### ISSUE TITLE
Issue with some script API

### ISSUE THREAD

**Issue by GEEKiDoS** [XLabsProject/iw6x-client#264]
```suicide``` and ```finishplayerdamage``` throws a script execution error, and player goes to some sort of semigod mode(can't die, but the blood is on the screen)

```radiusdamage``` just crashes the server.

my code:
```Lua
player:suicide();
```
```Lua
player:finishplayerdamage(player, player, 1000, 0, "MOD_EXPLOSIVE", "none", vector:new(0,0,0), "NONE", 0);
```
```Lua
game:radiusdamage(player.origin, 10, 500, 500, player);
```

Minidump from radiusdamage crash:
[iw6x-crash-2-2020-12-20-01-32-33.zip](https://github.com/XLabsProject/iw6x-client/files/5719916/iw6x-crash-2-2020-12-20-01-32-33.zip)

**Comment by momo5502** [comment]
Semms like dieing doesn't work anymore.

**Comment by GEEKiDoS** [comment]
> Semms like dieing doesn't work anymore.

But suicide with grenade works

**Comment by momo5502** [comment]
The issue appears cause G_RunFrame stores a variable inside the TLS. It is cleared after G_RunFrame. Our frame callbacks are executed outside G_RunFrame, which is the issue

**Comment by jonashofmans97** [comment]
I still have this issue
