### ISSUE TITLE
Rank doesnt increase, score and squad points also not saved 

### ISSUE THREAD

**Issue by SchunkelmannPeter** [XLabsProject/iw6x-client#265]
I've been playing for hours and no matter how many points I get, my rank stays at 1 and I dont even get any points added to it, I also don't get squad points, why? Its so weird, I've been playing on rank 1 for 4-5hours now

**Comment by SchunkelmannPeter** [comment]
Also non of the operations progress is being saved or tracked.

**Comment by OneFourOne** [comment]
Dedicated servers are unranked, ofc you aren't. Make classes in private match.

**Comment by momo5502** [comment]
See #101
