### ISSUE TITLE
When i open TW6X it just closes

### ISSUE THREAD

**Issue by TuDzVeNo** [XLabsProject/iw6x-client#273]
[iw6x-crash-1-2020-12-22-17-00-04.zip](https://github.com/XLabsProject/iw6x-client/files/5732234/iw6x-crash-1-2020-12-22-17-00-04.zip)

**Comment by momo5502** [comment]
This is an issue with your GPU. Try updating your drivers.

**Comment by TuDzVeNo** [comment]
ok

**Comment by TuDzVeNo** [comment]
they are up to date and still crashing

**Comment by momo5502** [comment]
Try reinstalling them. Enumerating the outputs fails ( https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgiadapter-enumoutputs ). This is an issue with your GPU, your display or your drivers. Nothing we can do.
