### ISSUE TITLE
Loading more than 1 script causes some issue

### ISSUE THREAD

**Issue by GEEKiDoS** [XLabsProject/iw6x-client#275]
Some functions are not working with that.
And the game crashes on `fast_restart` without a minidump.

Update 2:
Seems like the string argument can not recognized by `scripting::lua::convert(const sol::lua_value& value)` and returns a empty script_value, I printed the converted value from that function and this is the output:

With more than 1 scripts:
```
calling giveweapon
unknown arg wtf
************** Script execution error **************
Error executing function 'giveweapon'
stack traceback:
	[C]: in method 'giveweapon'
	...f Duty Ghosts\iw6x\scripts\infected-mod\player\equip.lua:10: in function <...f Duty Ghosts\iw6x\scripts\infected-mod\player\equip.lua:2>
****************************************************
```
With only 1 script:
```
calling giveweapon
string arg iw6_p226_mp
```

Update:
~The crash can't reproduce on my side anymore idk, but I have debugger attached before and the breakpoint was on this line:
https://github.com/XLabsProject/iw6x-client/blob/ac7d07aac3253578f1adba434cabd3c715e1ecb0/src/client/game/scripting/lua/context.cpp#L243`~ No, it's not the problem, my bad

But the function not working issue is still here:
Video from me:
https://streamable.com/73idmh

Video from @DoktorSAS with a crash:
https://streamable.com/xm0xe4
(crash not on `fast_restart` but map loading)

**Comment by diamante0018** [comment]
I believe this does not apply anymore after the addition of GSC scripts.
