### ISSUE TITLE
Game Freezes

### ISSUE THREAD

**Issue by ECicek33** [XLabsProject/iw6x-client#276]
After 1 Game of iw6x, my PC freezes on the loading screen of the next map, when I press the Windows key, it reacts but nothing happens, there are no minidumps that occur of that. I'm on the latest Version.

**Comment by momo5502** [comment]
Please create a process dump ( https://support.kaspersky.com/common/diagnostics/12401 ), when the game freezes. Zip it, upload it to google drive and link it here.

**Comment by ECicek33** [comment]
> Please create a process dump ( https://support.kaspersky.com/common/diagnostics/12401 ), when the game freezes. Zip it, upload it to google drive and link it here.

I have tried to do that but it still wont open Task manager, it opens but still blackscreen, i can close other applications with alt + f4 but not iw6x. So im not able to create dumps from it, very strange bug.

**Comment by diamante0018** [comment]
Closing this as no dump was provided, issue is very old and most likely does not reflect the current state of the client.
If OP reads this: try again to play the game and let us know if you encounter this issue again
