### ISSUE TITLE
linkto function not working

### ISSUE THREAD

**Issue by Slykuiper** [XLabsProject/iw6x-client#278]
I'm sure it's all set up properly, but when I call linkto() on an entity I get a script execution error

- attempt to call a nil value (method 'linkto')

enablelinkto() is enabled on the parent entity. playerlinkto() works perfectly but thats for linking the player to an entity. I need to link a non-player entity to another non-player entity.

**Comment by momo5502** [comment]
player:linkto should be working

**Comment by Slykuiper** [comment]
> `player:linkto(...)` should be working. Are you sure you used `:` and not `.` for function calls?

ah i figured it out, thanks
