### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Mario0708** [XLabsProject/iw6x-client#280]
[iw6x-crash-2-2020-12-25-21-26-17.zip](https://github.com/XLabsProject/iw6x-client/files/5742422/iw6x-crash-2-2020-12-25-21-26-17.zip)

**Comment by momo5502** [comment]
It crashes in RB_ProcessShaderUploads. Likely a GPU issue. Try updating or reinstalling your drivers

**Comment by diamante0018** [comment]
Closing this is as OP didn't not reply therefore we can assume he update/reinstalled their drives and all went well
