### ISSUE TITLE
Branding Text

### ISSUE THREAD

**Issue by hosseinpourziyaie** [XLabsProject/iw6x-client#297]
not an issue but at least there should be a dvar to let player hide upper-left branding text just like in iw4m

for content creators its annoying as its wrapping game screen

![iw6x 2020-11-29 12-43-31-786](https://user-images.githubusercontent.com/22142481/103679424-0c9b6300-4f9a-11eb-8413-e115dc369063.jpg)

**Comment by ChxseH** [comment]
I disagree. The developers should be credited for their work.

**Comment by OneFourOne** [comment]
The real issue here is that you're still on v1.0.3, please update to v1.1.0.

**Comment by hosseinpourziyaie** [comment]
> The real issue here is that you're still on v1.0.3, please update to v1.1.0.

dont act funny. besides I got this shot from archive; I already run latest update

**Comment by momo5502** [comment]
This won't be done. The branding is extremely small and unobtrusive.
If this is really such a big issue, people can disable it by compiling the client themselves, but we won't add a dvar for that.
