### ISSUE TITLE
When opening the IW6X application and selecting multiplayer, IW6X stays on a black screen while trying to load in Multiplayer

### ISSUE THREAD

**Issue by TORQSupercharged** [XLabsProject/iw6x-client#301]
I'll try to describe it the best as I can.
1. Clicked on the iw6x.exe (it's in the game folder)
2. Clicked on multiplayer.
3. game is loading but stays as a black screen and eventually will crash.
I've had members in the discord say to add the .dmp files here so I will do that. Also, they've also said that its an issue that multiple users are having so I'm not sure if it has been figured out yet, but read guessing that it's somewhat of a widespread problem.
**.dmp google drive link**
[https://drive.google.com/file/d/1k-WU7WUyS7Jut1HZQlPe2IcPBghHkhoU/view?usp=sharing](url)

**Comment by momo5502** [comment]
Here's a clickable version of your url. Cause you goofed it.
https://drive.google.com/file/d/1k-WU7WUyS7Jut1HZQlPe2IcPBghHkhoU/view?usp=sharing

**Comment by TORQSupercharged** [comment]
if you can, close this post. I ended up solving the issue myself.

**Comment by nate0247** [comment]
> if you can, close this post. I ended up solving the issue myself.

How did you fix it

**Comment by IMMORTALVASILIY** [comment]
Yes, How do you solve this? May someone please assist
