### ISSUE TITLE
Maps are stuck infinitely loading

### ISSUE THREAD

**Issue by TORQSupercharged** [XLabsProject/iw6x-client#302]
The game is stuck infinitely loading into maps in a private match and even when trying to join servers. 

**.dmp file here:** https://drive.google.com/file/d/1GT5vpGl9spXFwTyHxHJ4z00bYAtjFlwS/view?usp=sharing
  
Correct my link if it's bad cause I'm not good at GitHub lmao.

**Comment by IMMORTALVASILIY** [comment]
@TORQSupercharged  I hate when that happens, I really wanna play the GAME!!!!! I am sure they will fix it.

**Comment by momo5502** [comment]
> @TORQSupercharged  I hate when that happens, I really wanna play the GAME!!!!! I am sure they will fix it.

Please refrain from commenting unnecessary things. This is neither helpful, nor will it speed up things in any way. This just spams notifications.

**Comment by diamante0018** [comment]
You should try again. An issue with maps not loading was fixed not too long ago so this may have been fixed. Use the xlabs launcher to run the latest iw6x. Please let us know

**Comment by diamante0018** [comment]
Closing as extremely out of date and does not reflect the current state of IW6x.
OP is welcome to try again using latest iw6x and to let us know how that goes
