### ISSUE TITLE
the link to download ix6w wont work

### ISSUE THREAD

**Issue by cuackoo** [XLabsProject/iw6x-client#303]
whenever i click on teh links (Click here to get the latest release or the other one) it sends me to a blank page that says  {"message":"Build not found or access denied."} & {"message":"Artifact not found or access denied."} idk what to do as im no expert in this so maeby im doing somethimg wrong but trying to dowload it before or after the "code" wont work, please help

**Comment by playboy737** [comment]
@cuackoo same her I think it might be down I'm not sure have been trying to get it all night
