### ISSUE TITLE
Dedicated Server crashing

### ISSUE THREAD

**Issue by TheGamerX20** [XLabsProject/iw6x-client#305]
Hello! I ran a dedicated server for the Extinction game mode, and it just keeps randomly crashing.. it works well for a while then crashes like mid-match, custom games work fine though(at least so far), I asked on Discord and was told to post it here.

Here's my minidump: https://drive.google.com/file/d/1tG_vRfb1qaoVgQGXJOy8GhbNj0VvClQp/view?usp=sharing

Regards! :)

**Comment by efinst0rm** [comment]
This was mostly fixed with this commit #608
