### ISSUE TITLE
Game goes to black screen when launching with no information in the iw6x console and stops responding

### ISSUE THREAD

**Issue by nate0247** [XLabsProject/iw6x-client#308]

**Comment by parzahs** [comment]
yea i got the same thing I've even reinstalled my game

**Comment by IMMORTALVASILIY** [comment]
yet it still doesn't work
has something happend to the Program?

**Comment by diamante0018** [comment]
This does not provide any info to work with. 
Please try again with the latest iw6x build
https://xlabs.dev/support_iw6x_client

If I don't hear back from you in a bit I might have to close this issue.
