### ISSUE TITLE
2.0.0 server not responding

### ISSUE THREAD

**Issue by skiff** [XLabsProject/iw6x-client#315]
After updating to version 2.0.0 the server goes into a "not responding" state after some time. I've uploaded some crash dumps [here](https://drive.google.com/file/d/1reatJs6LXaq6WezIzGEB-jfC2Dss44UV/view?usp=sharing). I've tried to do a little bit of debugging myself and it seems to be related to bdLobbyService::pump and eventually a call to CloseHandle. 

I tried to do some debugging with it, but didn't really make any progress. Hopefully someone can make more sense of it than I can.

**Comment by skiff** [comment]
related to #314 typing in chat breaks both private match and the server

**Comment by skiff** [comment]
Something seems to be wrong with the scripting getEntByNum as [this](https://github.com/XLabsProject/iw6x-client/blob/5376df423490ba042724720cad869537c6c46035/src/client/component/logfile.cpp#L32) is where the game decides it no longer wants to work

**Comment by momo5502** [comment]
I really did an oopsie
