### ISSUE TITLE
r_Lod console commands don't work correctly

### ISSUE THREAD

**Issue by BoxOfMysteriez** [XLabsProject/iw6x-client#318]
Console commands such as r_lodBiasRigid and r_lodBiasSkinned are able to be changed but don't actually take effect in game. Other r_lod commands can't be changed at all, whether or not sv_cheats is enabled. I recall these working fine in IW4x so I'm hoping in IW6x it can be the same.

**Comment by diamante0018** [comment]
Won't add. Too much work for such an unpractical feature.
