### ISSUE TITLE
Cant launch mayday extinction map on iw6x

### ISSUE THREAD

**Issue by TheSuperion** [XLabsProject/iw6x-client#319]
Error code is given when trying to launch the map. I have tried the other extinction maps and they work fine so its just this one.
![iw6x_2021-01-19_09-55-59-755](https://user-images.githubusercontent.com/77705011/105109494-a24eec00-5a8a-11eb-8790-b92dbb797cbd.jpg)

**Comment by BoxOfMysteriez** [comment]
Getting this same message now, something must've broke with this on the recent updates. Worked fine before.

**Comment by cuackoo** [comment]
i got the same error on mayday

**Comment by GodRemembers** [comment]
Download v1.1.0 replace the one in your directory folder then turn off your internet access then boom Mayday. Temporary fix for solo players until they fix it 2.0.0 doesn't work either.

**Comment by OneFourOne** [comment]
This issue is related to #267. Commenting out the new code and putting the old back allows the map to load.

**Comment by FragsAreUs** [comment]
I will look into it and if needed reverting it so people can play on mayday
