### ISSUE TITLE
Fatal error when launching game 

### ISSUE THREAD

**Issue by VidhunNagarajan** [XLabsProject/iw6x-client#323]
When i launch singleplayer or multiplayer in the iw6x client, i get a fatal error. Minidump is attached below. The error is attached below. Please help. This is the first time i have submitted a bug report, btw.
![Capture](https://user-images.githubusercontent.com/69668645/105320287-f5e34600-5c00-11eb-9923-fccffad461fb.PNG)

[iw6x-crash-1-2021-01-21-15-46-23.zip](https://github.com/XLabsProject/iw6x-client/files/5847643/iw6x-crash-1-2021-01-21-15-46-23.zip)

Edit: i do get a message that my ram is below the requirements. I found that i have 4 gb ram but the requirements is 6 gb. Is this part of the reason for the error?

Edit 2: i have the latest graphics card updates and my pc is up to date.

**Comment by tuxtech1** [comment]
When will a fix be available

**Comment by tuxtech1** [comment]
Excuse me, when will a fix be available? I've been wanting to play IW6X for a long time.  I'm not stressing you do do it faster, please do not misunderstand.

**Comment by momo5502** [comment]
Dude, your PC doesn't meet the required specs, you answered it yourself.

**Comment by tuxtech1** [comment]
I know, but I heard that it can be run under 4 gb ram.

**Comment by FragsAreUs** [comment]
who ever told you that is a lied to you

**Comment by diamante0018** [comment]
Closing this as issue is OP's pc does not meat the minimum system requirements. Not an issue with iw6x
