### ISSUE TITLE
Unable to load import 'AgsDelnit'..?

### ISSUE THREAD

**Issue by Ryvnn** [XLabsProject/iw6x-client#336]
Hi,
i just downloaded iw6x and i tryied to install it, but i get this message that tells me this : https://prnt.sc/yit4du
If anyone can help me pls..

**Comment by Dss0** [comment]
This is most likely related to broken/incomplete files, not an IW6x issue. Prolly best to ask in the support channel on discord.

**Comment by Cartaxo1906** [comment]
> Hi, i just downloaded iw6x and i tryied to install it, but i get this message that tells me this : https://prnt.sc/yit4du If anyone can help me pls..

Where you able to fix it? i still  havent found a way to.
