### ISSUE TITLE
Loadout Bug

### ISSUE THREAD

**Issue by 29Asym** [XLabsProject/iw6x-client#358]
Every time I make or edit a loadout it does not appear in game as the one I made in the menu.

Please help. Thanks!

**Comment by BoxOfMysteriez** [comment]
You're supposed to make it private match.

**Comment by OneFourOne** [comment]
https://xlabs.dev/iw6x_faq.html
Q: My classes don't work online?
A: For now, you must make classes in private match. 

As of now dedicated servers are unranked. See #101

**Comment by 29Asym** [comment]
Thanks Guys it worked! I will not close this
