### ISSUE TITLE
iw6x still crashing with latest update (v2.02)

### ISSUE THREAD

**Issue by VenomCrown** [XLabsProject/iw6x-client#373]
Hello, I decided to try the new v2.02 update for iw6x.

I'm still getting freezes/crashes during multiplayer custom game with bots. It's not as bad as the last update, but it's still occurring unfortunately :(

I am posting my DMP file here. This is my own gdrive so this is legit my own. I hope you can take a look at it and see if there are any issues that maybe on my end or so.

https://drive.google.com/file/d/19IL_qFo4Qi0muaaL46VxQPfrJ-g2rtNO/view?usp=sharing

Playing on RTX 2080 with just high settings, off Physx, off lod and everything else.

Thank You

**Comment by VenomCrown** [comment]
So I was able to read the DMP file using WinDBG.

What does this all mean?

"KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 8390

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 8843

    Key  : Analysis.Init.CPU.mSec
    Value: 234

    Key  : Analysis.Init.Elapsed.mSec
    Value: 56027

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 282

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 199221

    Key  : Timeline.Process.Start.DeltaSec
    Value: 376

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Timestamp
    Value: 2019-12-06T14:06:00Z

    Key  : WER.OS.Version
    Value: 10.0.19041.1

    Key  : WER.Process.Version
    Value: 2.0.2.962


NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 0000000000000000
   ExceptionCode: 80000003 (Break instruction exception)
  ExceptionFlags: 00000000
NumberParameters: 0

FAULTING_THREAD:  0000069c

PROCESS_NAME:  iw6x.exe

ERROR_CODE: (NTSTATUS) 0x80000003 - {EXCEPTION}  Breakpoint  A breakpoint has been reached.

EXCEPTION_CODE_STR:  80000003

STACK_TEXT:  
00000000`013ff928 00007ffc`3040a34e     : 00000000`00000000 00007ffc`3044e88b 00000000`00000001 00000001`405e59f0 : ntdll!NtWaitForSingleObject+0x14
00000000`013ff930 00000001`40424466     : 00000000`00000024 00000000`00000001 0000015e`00000000 00000000`00000984 : KERNELBASE!WaitForSingleObjectEx+0x8e
00000000`013ff9d0 00000001`406213e3     : 00000000`00000024 00000001`404239ea 00000000`00000008 00000001`40501cd9 : iw6mp64_ship+0x424466
00000000`013ffa00 00000001`405e8668     : 00000000`000007d8 00000000`00000000 00000000`00000000 00000001`40158c8d : iw6mp64_ship+0x6213e3
00000000`013ffa50 00000001`402c9c95     : 00000000`000007d8 00000000`00000001 00000000`00000000 00000000`00000088 : iw6mp64_ship+0x5e8668
00000000`013ffaa0 00000001`404134d9     : 00000000`000007d8 00000000`00000000 00000000`00000000 00000000`00000000 : iw6mp64_ship+0x2c9c95
00000000`013ffae0 00000001`40413147     : 00000000`00000090 00000001`40000000 00000000`00000000 00000000`014f4059 : iw6mp64_ship+0x4134d9
00000000`013ffb20 00000001`40500b87     : 00000000`00000090 00000000`00000300 00000001`40000000 00000000`00000000 : iw6mp64_ship+0x413147
00000000`013ffb50 00000001`4073de00     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`0000000a : iw6mp64_ship+0x500b87
00000000`013ffca0 00000001`501df81e     : 00000001`00000000 00000001`4073dca4 00000000`00000000 00000000`00000000 : iw6mp64_ship+0x73de00
00000000`013ffce0 00000001`502cd96c     : 00000000`015268c0 00000000`00000000 00000000`00000000 00000000`00080000 : iw6x!SteamGameServer_Init+0xa086e
00000000`013ffef0 00007ffc`32bc7034     : 00000000`00000000 00000000`00000000 00000000`00000000 00007ffc`03ee0000 : iw6x!SteamUtils+0xec58c
00000000`013fff30 00007ffc`32d02651     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
00000000`013fff60 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21


STACK_COMMAND:  ~0s; .ecxr ; kb

SYMBOL_NAME:  kernelbase!WaitForSingleObjectEx+8e

MODULE_NAME: KERNELBASE

IMAGE_NAME:  KERNELBASE.dll

FAILURE_BUCKET_ID:  BREAKPOINT_80000003_KERNELBASE.dll!WaitForSingleObjectEx

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  10.0.19041.804

FAILURE_ID_HASH:  {6e08debd-ee31-ce56-32ef-878b2e67a5f2}

Followup:     MachineOwner
---------"

**Comment by CovertCollin** [comment]
Hey venom i have the same problem and this is the only thing that came up in my search. Did you ever find a fix?

**Comment by doomasl** [comment]
hey im also having this problem and searched every ware but didn't find anything if you find a fix please notify me.

**Comment by VenomCrown** [comment]
Okay, I finally got back to this game. It seems the client hasn't updated or did it got a new small patches?

Because I was able to play custom games with bots for 5 straight games without any freezes! Only time the client crashed is when I used F12 for screenshot and had one time freeze when loading the maps.

I can still use reshade and use it for screenshots. I did turn off the Steam so maybe that one time freeze was steam running on the background.

But most of the problems, it's no longer there. No more freezes on the custom menu when choosing guns etc.

I can finally enjoy Ghosts! And I can fully say that Ghost is fun as hell! Definitely going to be playing this for a long time alongside Modern Warfare 3 Plutonium and Black Ops 2 Plutonium!

Maybe it's the updates Nvidia has been putting out?

This is the current version that's installed on my PC right now.

GeForce Game Ready Driver Version: 471.11 
Release Date: 06/22/2021

Of course, if you have different cards like 3000 series. I don't know if it's still works. But, so far the game is running smooth now.

**Comment by doomasl** [comment]
Hey, I forgot about this comment i left. so sorry for not updating you guys, i got the crashes while i played R6S and i fixed the problem by simply updating my bios. Hope this helps and thank you @VenomCrown for the feedback.

**Comment by VenomCrown** [comment]
I was able to test 90% of maps and so far there's only one freeze which is Favela (MW3 Map).

I do 9 vs 9 (18 players) Matches with Friendly Fire On with custom scorelimit up to 200-300.

I tend to end the match around 15 mins or near all 20 mins.

I will keep testing other maps and hopefully I will let you know the ones that may cause more freezes in the future.

**Comment by mjkzy** [comment]
hey @VenomCrown, could you send the text file associated with the dmp file? specifically, the address where the error was said to occur?

**Comment by mjkzy** [comment]
also, the fix could be NVIDIA updating drivers, bios updates, etc. However, IW6x itself just got a little update but it was yesterday, way before you hopped back to play IW6x

**Comment by clx127** [comment]
I have to 2.0.2 version and yes my game too freezes... Before it wasnt. After each update we get new bugs;D

**Comment by VenomCrown** [comment]
Welp. It seems the new Nvidia updates are now back to freezing the game for me. Can't even start a match :\

GeForce Game Ready Driver Version: 471.41
Release Date: 07/19/2021

I don't understand why IW games after MW3 started getting issues on PC. MW1-MW3, I played campaign + Bot Warfare mods and cod4x/iw4x/Plutonium and I never gotten a single crash on either mods/client servers other than disconnects from online play.

Ghost and Infinite Warfare. I always have issues on custom games. Campaign however, Ghost actually performs well (I'm getting 180-250FPS with NO crashes + FOV Trainer + Trainer Mods. And Infinite Warfare is performing good.

But when it comes to custom games. Literally so many crashes T__T

**Comment by joshuabrey** [comment]
@VenomCrown bruh when i play custom games with bots in mid game i freeze then black screen it always frustrates me pls can u help me fix it

**Comment by diamante0018** [comment]
No reply was received.
Since the client is currently very stable and I got no reply since last message I will close this

If OP reads this again I encourage you to try again with the latest version
