### ISSUE TITLE
Support callback replacing in Lua

### ISSUE THREAD

**Issue by naccib** [XLabsProject/iw6x-client#377]
Currently, something like `level.onplayerdamage = function(...) print(...) end` will cause the following error:

``` sol: cannot set (new_index) into this object: no defined new_index operation on usertype
stack traceback:
[C]: in metamethod 'newindex'
```

Please consider adding a mechanism to define custom callbacks by either overriding the old ones like we do it in GSC or some other mechanism.

**Comment by momo5502** [comment]
Just use the event system. Callbacks like this also use the event system in GSC.

**Comment by naccib** [comment]
Thanks for the reply. Is there a way to prevent a weapon doing damage with events only?
