### ISSUE TITLE
Minidump when I try to load into any kind of game.

### ISSUE THREAD

**Issue by CCLA1902** [XLabsProject/iw6x-client#392]
![image](https://user-images.githubusercontent.com/83595427/116891248-19e8f700-abf4-11eb-9bfe-397adb8c37fb.png)
Would love to play the game but always get this error.
[iw6x-crash-2-2021-05-01-06-54-34.zip](https://github.com/XLabsProject/iw6x-client/files/6415548/iw6x-crash-2-2021-05-01-06-54-34.zip)
[iw6x-crash-2-2021-05-01-06-56-34.zip](https://github.com/XLabsProject/iw6x-client/files/6415549/iw6x-crash-2-2021-05-01-06-56-34.zip)
[iw6x-crash-2-2021-05-01-06-57-06.zip](https://github.com/XLabsProject/iw6x-client/files/6415550/iw6x-crash-2-2021-05-01-06-57-06.zip)
[iw6x-crash-2-2021-05-01-06-59-48.zip](https://github.com/XLabsProject/iw6x-client/files/6415551/iw6x-crash-2-2021-05-01-06-59-48.zip)
[iw6x-crash-2-2021-05-01-07-25-11.zip](https://github.com/XLabsProject/iw6x-client/files/6415552/iw6x-crash-2-2021-05-01-07-25-11.zip)
[iw6x-crash-2-2021-05-01-07-26-19.zip](https://github.com/XLabsProject/iw6x-client/files/6415553/iw6x-crash-2-2021-05-01-07-26-19.zip)
[iw6x-crash-2-2021-05-01-07-28-09.zip](https://github.com/XLabsProject/iw6x-client/files/6415554/iw6x-crash-2-2021-05-01-07-28-09.zip)
[iw6x-crash-2-2021-05-02-05-50-10.zip](https://github.com/XLabsProject/iw6x-client/files/6415555/iw6x-crash-2-2021-05-02-05-50-10.zip)
[iw6x-crash-2-2021-05-03-05-33-30.zip](https://github.com/XLabsProject/iw6x-client/files/6415556/iw6x-crash-2-2021-05-03-05-33-30.zip)
[iw6x-crash-2-2021-05-03-09-43-23.zip](https://github.com/XLabsProject/iw6x-client/files/6415557/iw6x-crash-2-2021-05-03-09-43-23.zip)

**Comment by mjkzy** [comment]
*problem seems to occur somewhere in bdInetAddr::bdInetAddr. internet/connection related?*

**Comment by CCLA1902** [comment]
no its not internet problem or connection

**Comment by momo5502** [comment]
> no its not internet problem or connection

Unless you investigated the dumps, I'm pretty sure you cannot make any statement on this.

**Comment by diamante0018** [comment]
@CCLA1902 please try again with the latest build from develop. You should use the xlabs launcher to ensure you are up to date

**Comment by diamante0018** [comment]
No reply from IP.
Please try again with the latest version of IW6x and let us know how it goes 😄
