### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by trailitita** [XLabsProject/iw6x-client#406]
I get the "mp_character_room_dlc_updated" error right after I get in the menu. Can someone give me a hand?

**Comment by OneFourOne** [comment]
> "mp_character_room_dlc_updated" error

This doesn't make sense by itself maybe you mean you're missing a file. Try finding your error [here](https://xlabs.dev/iw6x_errors) and if you can't figure it out still please come to the discord:  https://discord.gg/sKeVmR3
