### ISSUE TITLE
IW6x loading

### ISSUE THREAD

**Issue by IMMORTALVASILIY** [XLabsProject/iw6x-client#414]
whenver I launch a Private Match, it doesn't load up, it seems to load for about 5 minutes, which is too long for a Call of Duty Map to load, I also hope that xpartygo on online lobbies will work and the option to place bots, so I can level up while playing against bots.

**Comment by Ondrejko** [comment]
You say it doesnt load up and then say it loads up. Also you can add bots

**Comment by IMMORTALVASILIY** [comment]
It doesn't load up that is, I know you can add bots, It's that I can't even play with bots if I can't start a match because the loading is stuck or something

**Comment by momo5502** [comment]
Get a better drive if it takes too long to load

**Comment by IMMORTALVASILIY** [comment]
By Better drive you mean something for my PC?
