### ISSUE TITLE
Crash when launching: Fatal Error (0xC0000005) at 0x00000001405E5483.

### ISSUE THREAD

**Issue by Scarscruffy78** [XLabsProject/iw6x-client#421]
Minidump: 
[iw6x-crash-2-2021-05-31-12-45-23.zip](https://github.com/XLabsProject/iw6x-client/files/6571842/iw6x-crash-2-2021-05-31-12-45-23.zip)

![IW6X Crash Error](https://user-images.githubusercontent.com/60988127/120231505-c7a8ef00-c20e-11eb-87df-a31b8e71baa4.png)

**Comment by mjkzy** [comment]
@Scarscruffy78 looks like its something DirectX related or something on the lines of:
- "Direct X resolution mode"
- "No valid resolutions of %i x %i or above found"
- dvar "r_displayRefresh"

**Comment by diamante0018** [comment]
Because this is an issue in the function that initializes the game's renderer, I am keen to think there is something wrong on your end @Scarscruffy78.
Please join our discord server https://discord.gg/sKeVmR3 where we have posted a couple of things to try for directx errors.
