### ISSUE TITLE
Updater stuck in loop when no writing permission

### ISSUE THREAD

**Issue by Brentdevent** [XLabsProject/iw6x-client#433]
Updater seems to get in an infinite loop while updating when it doesn't have the right permissions. 

Running as admin/change the permissions fixes this issue for now.

**Comment by momo5502** [comment]
Doesn't really make sense to tackle that, as the launcher will deal with updates in the future, and it verifies that writing files to disk worked and reverts changes otherwise. So it shouldn't happen with the launcher.
