### ISSUE TITLE
Connecting local clients via private game causes the host game to close. 

### ISSUE THREAD

**Issue by PoundlandBacon** [XLabsProject/iw6x-client#440]
If you run multiple instances of iw6x on the same machine, and then host a private game on one instance, wait until the host is in game and connect to it via the console (connect 127.0.0.1) on the other instance(s) it will establish the initial connection but during loading the the host game will close and return to the main menu, leaving the connecting clients stuck on the load screen. 

Previous versions of the client (for sure 1.0 and the early patches) allowed for connections between clients running on the same machine (tested 4 simultaneously before), so it certainly can be done.

 I know this is using the client in a way in which it was not intended and I understand completely if this isn't something you wish to look at. That said it would be hugely appreciated if you do! Let me know if more information is needed.

**Comment by PoundlandBacon** [comment]
From further testing I have found that it stopped working with version 2.0

**Comment by mjkzy** [comment]
> From further testing I have found that it stopped working with version 2.0

do you know what specific commit this has started on?

also, IW6x isn't really meant to be ran with multiple instances tbh so this is stuff that is expected.

**Comment by diamante0018** [comment]
Cannot replicate with a dedicated server and client running locally

**Comment by PoundlandBacon** [comment]
Apologies, I should have updateded this. I found the issue is due to the way in which the ID key/numbers are generated in auth.cpp. I found that replacing lines 64-68 with lines 72 and 73 (Basically forcing a randomised ID) allowed multiple locally running clients to connect. I can only assume they all have the same ID if this change isn't made and therefore cannot successfully connect.

**Comment by diamante0018** [comment]
That's a non-issue. Guid needs to be them same because of tools lime IW4M
Since this is not a problem with just one client there is nothing to fix.
You can play with bots instead of connecting from multiple clients
