### ISSUE TITLE
scriptmodelplayanim() function no longer works

### ISSUE THREAD

**Issue by Slykuiper** [XLabsProject/iw6x-client#444]
It definitely worked when I made my last video but for some reason it doesn't work anymore.

Add this to __init__.lua

`game:precachempanim("mp_stand_idle")
`
and calling this function somewhere

```
function spawndummy(player)
    if dummy ~= nil then
	    dummy:delete()
    end
    dummy = game:spawn("script_model", player.origin)
    dummy.origin = player.origin
    dummy.angles = player.angles
    dummy:setmodel(player:getcustomizationbody())
    dummy:scriptmodelplayanim("mp_stand_idle")
end
```

Everything works except the animation

**Comment by diamante0018** [comment]
FIxed https://github.com/fedddddd/iw6x-client/commit/96da12df000718bf864b6d7ab7c5ca1478f0814e
