### ISSUE TITLE
Game wont load up

### ISSUE THREAD

**Issue by KeeganYoung** [XLabsProject/iw6x-client#447]
I start a single player game or a multiplayer game and it doesn't start, just stays in the loading screen... what should I do?

**Comment by momo5502** [comment]
Create a dump

**Comment by KeeganYoung** [comment]
How?

**Comment by momo5502** [comment]
https://letmegooglethat.com/?q=create+a+process+dump

**Comment by KeeganYoung** [comment]
Okay, what kind of dump? 
Replication dump, memory dump ect.?

**Comment by momo5502** [comment]
There is only one type of dump? A process dump...

**Comment by KeeganYoung** [comment]
Oh, sorry new to this🙈

**Comment by KeeganYoung** [comment]
![image](https://user-images.githubusercontent.com/77715954/127484884-f241b5a0-7fd9-4805-9fa8-52f8920aa6c7.png)
Does this even with dump...

**Comment by Brentdevent** [comment]
You open task manager and create a dump file of the IW6x process. 
If you need extra info how to, you can read more about it over here https://support.kaspersky.com/common/diagnostics/12401

Then post your dump over here.

**Comment by KeeganYoung** [comment]
Won't let me upload it...

**Comment by Brentdevent** [comment]
Probably because of the file size. Use a file hosting service you prefer. 
For example Google drive, Dropbox, Mega...

**Comment by KeeganYoung** [comment]
https://1drv.ms/u/s!AnPrLzQIXQnYjuJa6c392YFoZG6qug?e=IPGOoa

There we go, the dump file

**Comment by KeeganYoung** [comment]
Any word back on this?
Still having the same problem

**Comment by diamante0018** [comment]
> Any word back on this? Still having the same problem

Can you try to play again? I believe this issue was fixed not too long ago. Use the xlabs launcher

**Comment by diamante0018** [comment]
Please visit our website for up to date information on how to use our latest iw6x build.
Closing this as it is extremely outdated and many bugs relating to extinction maps not loading have been fixed and this may be one of them.
Thanks
