### ISSUE TITLE
Game freezes on any map

### ISSUE THREAD

**Issue by clx127** [XLabsProject/iw6x-client#448]
My client version 2.0.2 and in private match with bots on map BayView game randomly freezes and i cannot do anything, even cant close game it just stucks.... Im on windows 10 64 latest version

**Comment by momo5502** [comment]
Create a dump

**Comment by clx127** [comment]
> Create a dump

Sorry i restored old version of 1.10 and it works fine. Also i dont know how to create a dump

**Comment by clx127** [comment]
My game still freezes even on old version of 1.10. Before having issue i was on windows 8.1 then i upgraded my os to Windows 10 pro latest version. Previously on Windows 8.1 all was ok no freezes, now game just freezes when playing with bots on any maps:( I can play first some 7 minutes and after that game get freezes

**Comment by diamante0018** [comment]
The download link expired, could you try again with the latest version of iw6x @clx127
