### ISSUE TITLE
Game freezes randomly on private matches for many reasons [READ COMMENTS]

### ISSUE THREAD

**Issue by krookadile** [XLabsProject/iw6x-client#450]
In many gamemodes such as Infected you gain points at random times for surviving, and the IW6x console shows this command: 

**"bdNATTravClient::sendKeepAlive: Sending keep alive to introducer(s)."**

Everytime that command pops up in the console, my game freezes and I have to close it, it may be another reason why but I'm pretty sure it's that.

CPU : Ryzen 5-4600h
GPU : GeForce GTX 1650
RAM : 8 GB
STORAGE : SSD 256 GB

**Comment by krookadile** [comment]
I don't know what is causing the freezing, I'm just guessing that is one of the reasons

**Comment by krookadile** [comment]
The game has a small chance of freezing and not responding whenever the countdowns starts in a match as well, it doesn't crash, I have to close the game

**Comment by diamante0018** [comment]
Whe don't really count game freezes as game breaking bugs. The game does tend to crash often but the problem you are having is probably related to an issue on your end

**Comment by diamante0018** [comment]
Closing this as this is a simple "game client hanging for a moment every now and then".
Please try again with the latest iw6x version. Visit our website to get it.
I encourage the user to try again and post minidumps if further issues arise.
