### ISSUE TITLE
Launcher doesn't show any game modes while run on Proton 5.3-5

### ISSUE THREAD

**Issue by SSUPII** [XLabsProject/iw6x-client#457]
The launcher will only show a PLAY and ABOUT text and nothing else. 
![Istantanea_2021-08-04_22-08-32](https://user-images.githubusercontent.com/42090377/128248586-c35824ed-85e9-4e0b-ad02-4b658267f854.png)
Happens on both integrated graphics and NVIDIA Optimus enabled card (with [Bumblebee](https://wiki.debian.org/Bumblebee)).

Debian 10.10 Buster (amd64) with XFCE desktop environment.
Also happens on Wine 6.11, Wine 6.14, and Lutris.

Possible conflict with the Gecko engine?

**Comment by OneFourOne** [comment]
https://xlabs.dev/iw6x_errors#blank_launcher

**Comment by mjkzy** [comment]
What OneFourOne said is most likely the fix. However, to play new versions of IW6x now, i'm pretty sure you need to use the X Labs launcher (found here) https://master.xlabs.dev/data/xlabs.exe

**Comment by diamante0018** [comment]
The in-game launcher isn't used anymore since now it has been replaced by the xlabs launcher.
You may use a shell script to start iw6.exe with the -multiplayer parameter to skip the selection in the in-game launcher
