### ISSUE TITLE
maps do not load

### ISSUE THREAD

**Issue by MakuAureo** [XLabsProject/iw6x-client#458]
for some reason the extinction map mayday loads and is completely playable, but any other map (multiplayer or extinction) gets stuck at around 30% while loading

dump file: https://drive.google.com/file/d/1RLbCQCumuzheaKUh7LnQLzJVJdDioEEk/view?usp=sharing

**Comment by mjkzy** [comment]
dump file no longer working ^

**Comment by diamante0018** [comment]
Too old to work with
