### ISSUE TITLE
Any timeline for the next iw6x update?

### ISSUE THREAD

**Issue by VenomCrown** [XLabsProject/iw6x-client#465]
I just want to ask, since I checked the discord and there still hasn't been an update since v2.02 (5+ months now).

I also posted this on my issues back then.

https://github.com/XLabsProject/iw6x-client/issues/373

It work for awhile, but with the new recent Nvidia updates. It went back to causing constant freezing again on private matches/bots.

I was wondering if the mod author was able to find the issue or a way to really fix this? I am slowly enjoying Ghosts MP. Especially experimenting with their amazing specialist system (Best for sure).

But shame that I couldn't play that much due to this constant freezes.

Out of all the Golden Age of COD games (MW1-Ghosts) that I have played on PC.

Only Ghosts and Black Ops 2 had issues on PC. 

Ghosts works wonderfully on campaign (250FPS, Reshade, FOV Trainer, Trainer) No crashes watsoever in this.

MP on the other hand. Constant Freezes.

Black Ops 2 MP works Perfect, No crashes, but Campaign is full of crashes and freezes.I STILL haven't finished the campaign (almost at the end now) due to the freezes and crashes. Literally the only game that is unfinishable due to this.

**Comment by mjkzy** [comment]
no clue tbh. even though iw6x/s1x are new projects, the focus seems to be right back on iw4x (not from the main devs, but community mainly). other than that, main devs aren't working on this

**Comment by diamante0018** [comment]
Not an issue
