### ISSUE TITLE
Frequent Crashing on Dedicated Server

### ISSUE THREAD

**Issue by HollowWaka** [XLabsProject/iw6x-client#475]
dedicated server is crashing in a random but frequent manner. out of the 15 or so times i've ran the server, 10-12 of those would last longer than 15 minutes before crashing. the other 3-5 crashed in under 10 minutes. the crash error and address have been the same every time. the server has been run only on extinction every single time (across 2 maps); both of which it crashed on.

i've tried:
reinstalling graphics drivers
running server as administrator
repairing windows files (sfc /scannow in command prompt)
adding the server folder as an exclusion to windows firewall
having my friend try running the server on his pc (also crashed on his pc with the same exact error and address)

crash dump:
[iw6x-crash-3-2021-09-12-16-08-22.zip](https://github.com/XLabsProject/iw6x-client/files/7158603/iw6x-crash-3-2021-09-12-16-08-22.zip)

**Comment by efinst0rm** [comment]
This was mostly fixed with this commit #608
