### ISSUE TITLE
Fatal Error (0xC0000005) at 0x000000014041C66E 

### ISSUE THREAD

**Issue by AVRaVe** [XLabsProject/iw6x-client#485]
![image0](https://user-images.githubusercontent.com/92290015/136739282-c30f85e8-cd66-4a5e-ad58-18c25fffdb06.jpg)

I get this error every time I try and join one of my friends in private match or whenever I try and join a server. I've redownloaded my game multiple times and have tried numerous fixes. I have no idea where to go from here. Someone please help.

**Comment by diamante0018** [comment]
I would like to give you the opportunity to have a look in your game folder and see if you still have this minidump.
Highly unlikely since this post I old. I hope I hear back from you within 7 days.

**Comment by AVRaVe** [comment]
Yea I don’t have it anymore. Factory resetting my pc and redownloading
fixed it.

**Comment by diamante0018** [comment]
Okay glad you fixed it
