### ISSUE TITLE
"xpartygo" does not work.

### ISSUE THREAD

**Issue by ghost** [XLabsProject/iw6x-client#495]
Not sure if it's a bug or not, but since the console auto-completes I thought I should post.
I was trying to level up with bots.

**Comment by callme6** [comment]
anyone have any issues ?

**Comment by FragsAreUs** [comment]
ghost does not have ranked as of right now so xpartygo is usless as there is currently no way to level up

**Comment by diamante0018** [comment]
Duplicate of #101
