### ISSUE TITLE
Black Screen Upon single/multi-player Selection

### ISSUE THREAD

**Issue by Black-Shack** [XLabsProject/iw6x-client#502]
Hi,

When trying to select Singleplayer the game launches to a black screen with the IW6x version in the top left but nothing else and then freezes on the black screen instead of bringing up the in-game menus. When launching Multiplayer the game launches to a black screen with nothing (no version top left) and then stops responding.

List of things I have already tried:

- Reinstalling the game files
- Updating graphics drivers to the latest software available (see below)
- Closing all overlays including Steam
- Running .exe file as administrator 
- Ran a redist installer recommended to me by someone on the iw6x discord
- Restarting my laptop

These were all the suggestions I received from the discord support server but unfortunately, none of them succeeded. So I was sent here to make a post in hopes that someone else could maybe provide some assistance.

Thanks for your time,
any help at all would be greatly appreciated

![Screenshot 2021-10-29 105209](https://user-images.githubusercontent.com/93374888/139406374-a7ebaa2a-3db7-4df6-ba81-6d478d987e91.png)
[iw6x-crash-2-2021-10-30-11-46-41.zip](https://github.com/XLabsProject/iw6x-client/files/7446248/iw6x-crash-2-2021-10-30-11-46-41.zip)

**Comment by akaSteam** [comment]
I have the same problem.

**Comment by akaSteam** [comment]
Please let me know how to fix if you have yet

**Comment by alexhampu** [comment]
I had the same issue, and I found out what was causing it by running the Steam version, without any modifications and it had the same problem.

I have a dual monitor setup, and one of them runs on the integrated GPU and the other on the dedicated GPU. I have switched Windows to only use the main monitor that's plugged in the dedicated GPU and it worked.

For laptops you can try changing the setting the preferred GPU in the "Graphics settings" form Windows 10 to use the dedicated GPU, maybe it works.

**Comment by LYEddie** [comment]
I also had the same problem, and it seems that it was a compatibility error with Windows 11, black screen in both MP/SP, also, it seems that you have to disable full screen optimizations:

Windows 11: nothing

I tried downgrading to Windows 10 1709 (2017), using video drivers from 2017 (intel UHD 610), installing VC++ Redists from 2005 to 2019 x86/x64, and updating directX, now it works, but i had to lower the render quality to low/medium.

You can also try activating/deactivating fullscreen optimizations, in the properties/compatibility tab of the game executable.
![image](https://user-images.githubusercontent.com/70493362/152425508-23f5e08d-cf46-4d0e-9508-2ea80578b1ac.png)

**Comment by diamante0018** [comment]
Has op tried anything that was suggested?

**Comment by diamante0018** [comment]
@Black-Shack could you please come back to this issue, try again with the latest develop build and follow the advice the other people gave you?

**Comment by diamante0018** [comment]
Please follow the advice you were given. Also it might have been the case you had Steam opened which interfered with iw6x.
Please visit our website for up to date information on how to use the latest version of iw6x
