### ISSUE TITLE
NEEDS OFFLINE INSTALL OPTION

### ISSUE THREAD

**Issue by ForeskinJohn** [XLabsProject/iw6x-client#515]
Used to, i never needed an internet connection to install my IW6X file, but now i do, if i could at least find out where these files are downloaded, i could back them up for offline install, but in the meantime i have to use goldberg. Please fix this, as I was told that X-Labs would always stay offline friendly, this is now no longer the case and its a damn shame.

**Comment by yolarrydabomb** [comment]
AppData\Local\xlabs\data\iw6x

**Comment by ForeskinJohn** [comment]
thanks m8
