### ISSUE TITLE
Mayday Stopped Working Again

### ISSUE THREAD

**Issue by TheSoliderror** [XLabsProject/iw6x-client#536]
Mayday does not work in servers and as far as I tell people have posted that they cannot launch it via in game either, this used to happen with an older version of iw6x but last I can remember it was fixed and now its no longer working. If I load if up within the server it does not start the server and it does not work thus I removed it from my map chooser for now until the maps works correctly again. @momo5502 I would like this issue fixed asap so people can play that map as my server is the only extinction server up at the moment and I would say it is the best extinction map that there is and I liked to have it be saved as my default map that people play on when the server is restarted. Thank you!

**Comment by diamante0018** [comment]
What error does it give if any? (Dedicated and Multiplayer)
When did it last stop working?
When did it start working again?
Did it stop working recently?

**Comment by TheSoliderror** [comment]
@diamante0018 It does not give an error it gives an overflow as does the game error. Here is the game error same servers overflow 
![error](https://user-images.githubusercontent.com/83806741/149836230-9f8220ae-63c4-4a7d-8023-0869320c9c10.png)

**Comment by fedddddd** [comment]
#509

**Comment by TheSoliderror** [comment]
> #509 

When did you start dping again? Last I head from you, you got banned on Pluto. Never fot the full story on that lol
