### ISSUE TITLE
Cannot join local server with local IP

### ISSUE THREAD

**Issue by TheSoliderror** [XLabsProject/iw6x-client#539]
This issue arose at the same time as mayday broke once more, however this was not updated out. Mayday now works fine but with the new versions of iw6x I cannot join my server with the local IP and I need this as my router does not support NAT loopback at the moment. I use the IP 192.168.1.126:27016 and it tries to join but it tells me the maps fast file does not match the servers. However if I use a Iw6x.exe that fed has given me to use for my server to fix mayday it lets me join just fine. If the Iw6x.exe I use is needed to help let me know and I can send it over or just ask fed for it.

**Comment by mjkzy** [comment]
is mayday not fixed on the client as a whole?

**Comment by TheSoliderror** [comment]
> is mayday not fixed on the client as a whole?

Last update it had an overflow error but now I think its fixed for the most part, but I couldnt get my server to run mayday unless I used Feds iw6x.exe. Alsonon my pc it told me I need to update my graphics card only on that map so im also using itnto play mayday as well.

**Comment by yolarrydabomb** [comment]
What happens if you try 127.0.0.1:27016
