### ISSUE TITLE
The console command "r_aspectratio custom" should be checked...

### ISSUE THREAD

**Issue by LYEddie** [XLabsProject/iw6x-client#549]
I'm having some trouble setting the resolution to 1920x720, aspect ratio 8:3 or 2.66667 in decimal, and once activated, it doesn't make changes and the game continues with the screen and GUIs stretched, too, from what I've seen in the repository iW6x if there is support for ultrawide monitors, but it may only work with multiples of 1080p (dual or triple monitor). since the command exists, it would be great if it could be enabled or fixed, because in iW4x (MW2) it works correctly
![unnamed](https://user-images.githubusercontent.com/70493362/152430412-a621180e-6266-4110-90a8-f527e90262eb.png)
.
The first image shows the stretched game menu, and the second is a "prototype" of how it should look, it's a correction I made with mspaint, it still didn't fix anything.

**Comment by Brentdevent** [comment]
Did you also change `r_aspectRatio auto` to `r_aspectRatio custom`? \
Because the screenshot tells something different.

You have to set `r_aspectRatio custom` and `r_aspectCustom 2.66667`

after that you type `vid_restart` and then it should apply the changes.

**Comment by LYEddie** [comment]
... well, it has worked. I suggest adding that information to a wiki or I don't know, it could be useful for someone else, thanks, issue closed.
