### ISSUE TITLE
Server Query Info

### ISSUE THREAD

**Issue by TacTicTow** [XLabsProject/iw6x-client#568]
Can you implement the ability to query the IW6 and S1X servers so I can create game server banners for our site and forums? 

I want to be able to creat ebanner form that info like this...

https://saltybawls.com/lgsl/userbar.php?s=21&t=2

Thanks!!

**Comment by momo5502** [comment]
This is already possible. You just need to query them. The entire communication around X Labs follows the old quake/dpmaster protocol described here: https://github.com/kphillisjr/dpmaster/blob/master/doc/techinfo.txt
Just send getInfo requests to the servers and you'll get an infoResponse back: https://github.com/XLabsProject/iw6x-client/blob/develop/src/client/component/party.cpp#L470

**Comment by TacTicTow** [comment]
Hi there!

Just wanted to say thank you. Your response was the first meaningful and helpful reply I have gotten. As a result of that info I was indeed able to query my servers and create my server banners. So thank you!

I was curious though, I do not seem to be able to poll any player info. I can get the numbers of players online ‘clients’ and but it does not show the playername or pings etc. Am I missing something?

Thanks…
