### ISSUE TITLE
Dedicated server Error 0xC0000005

### ISSUE THREAD

**Issue by TheAnsuz** [XLabsProject/iw6x-client#586]
Running a dedicated server (tryied on two computers) gives me the same error, **it happens randomly** during the match in **extintion mode** (haven't tried on other gamemodes).

Seems to occur randomly when a mission gets completed/failed or when a hive is destroyed.
- Version: v3.0.2
- Environment: Dedicated Server
- Timestamp: 2022-04-10-20-01-42
- Clean game: Yes
- Exception: 0xC0000005
- Address: 0x1403A1A06
- OS Version: 6.2

[iw6x-crash-3-2022-04-10-20-01-42.zip](https://github.com/XLabsProject/iw6x-client/files/8459653/iw6x-crash-3-2022-04-10-20-01-42.zip)

**Comment by mjkzy** [comment]
crashes in UpdateLastSeenPlayers(), trying to reference a variable for something. do you run any scripts?

**Comment by TheAnsuz** [comment]
No, the server is as default, no modifications of any kind

**Comment by efinst0rm** [comment]
This was mostly fixed with this commit #608
