### ISSUE TITLE
IW6X cannot load into any multiplayer match or anything in

### ISSUE THREAD

**Issue by moonshine61** [XLabsProject/iw6x-client#592]
so i downloaded the game with client and dlc and when i loaded the game up, the game came up no problem. so i went to join a server, and now it just gets stuck and just keeps trying to load. i left it alone for a while and still was stuck.

**Comment by diamante0018** [comment]
Could you provide more info? Does this issue happen only when joining 'a' server or any server?

**Comment by diamante0018** [comment]
No useful info was provided by OP so I'm closing this. Not much information to go off here
