### ISSUE TITLE
Framedrops and very short game freezes?

### ISSUE THREAD

**Issue by erniberni1611** [XLabsProject/iw6x-client#630]
I have IW6X since about two weeks, everything worked fine, installing, unlockstats, etc.
But since two-three days the game is just unplayable for me. My FPS drops so extremely every now and then and the game freezes so often that you can't do anything anymore. What can be the reason for this? (sorry for my bad English)

**Comment by diamante0018** [comment]
Not an issue with the client. The game runs fine with a good gaming computer.
Please join the xlabs discord and ask there to get further information
