### ISSUE TITLE
Implement Lagometer

### ISSUE THREAD

**Issue by SoyRA** [XLabsProject/iw6x-client#65]
Implement the Lagometer but with 2 new things if possible.

The first "new thing" would be this:
```c
// Enable the 'lagometer'
// "0" - Off
// "1" - On
// "2" - On but only shown when you press Esc (the new thing)
drawLagometer "2"
```

The Lagometer shows the ping but only on the graph, the other "new thing" is that the Lagometer says below the ping number.
  \* This part could be interesting if you can't see the ping on the scoreboard and so on.

**Comment by diamante0018** [comment]
Not planned due to the complexity.
