### ISSUE TITLE
Dedicated servers lag/run at double speed

### ISSUE THREAD

**Issue by OneFourOne** [XLabsProject/iw6x-client#67]
🛠️

**Comment by Joelrau** [comment]
Seems to be related to com_maxfps ?

**Comment by momo5502** [comment]
I can't reproduce this either. Can you please check if it's still valid?

**Comment by TheGamerX20** [comment]
I have this even on private matches.
Can show you some recordings if you like?

**Comment by momo5502** [comment]
> I have this even on private matches.
> Can show you some recordings if you like?

If you have it in private match, it's probably just your CPU being bad 😂

**Comment by Silentcer** [comment]
i can also confirm 1 CPU core pegged at 100%.
CPU is a E5-2687A-V4 on a VPS. ran 14 IW4x servers no problems
![Capture](https://user-images.githubusercontent.com/73448937/97122233-a49ae780-16e1-11eb-82e5-0cc4acee86f2.PNG)

**Comment by TheGamerX20** [comment]
> 
> 
> > I have this even on private matches.
> > Can show you some recordings if you like?
> 
> If you have it in private match, it's probably just your GPU being bad 😂
> Please upload the recordings though

an RTX 2070 Super isn't enough for IW6? :P
while trying to reproduce it I found out that it happens mostly if I alt+tab,
I guess that causes some desync with the game or something, my bad, sorry. :/
probably was too excited by sharing IW6x around, was taking lots of screenshots :P

**Comment by ChaseHall** [comment]
Can confirm dedis do some form of "hitching" [here's a video of what happens](https://streamable.com/5wxh4h).
