### ISSUE TITLE
IWX6 not working 

### ISSUE THREAD

**Issue by Cissu** [XLabsProject/iw6x-client#691]
![B2675FBF-2206-4C67-BBC8-CA51BD909DB5](https://user-images.githubusercontent.com/115377819/194732742-ee60825f-70e4-44a8-9bf8-1a7c5fb58d86.jpeg)

when ever I try to play multiplayer either offline with bots or online this error shows up

The Call of Duty: Ghosts server is not available at
this time. Please try again later or visit
http:/ /www.callofduty.com/ghosts/status for
updates.

**Comment by diamante0018** [comment]
Please wait for people to reply to you in the iw6x-support channel before rushing to create an issue on the GitHub. You may have issues reaching the game's servers (demonware) which in that case would not be an iw6x issue
