### ISSUE TITLE
Spawnbot at dedicated server just create bots with character captain price only

### ISSUE THREAD

**Issue by amrurikaj** [XLabsProject/iw6x-client#693]
I don't know whether this is a problem or not but to me it's quite annoying that all bots are captain price.  :-D

**Comment by diamante0018** [comment]
Not a bug worth fixing

**Comment by amrurikaj** [comment]
@diamante0018 should let it open? or close it?but still annoyed with the captain price 😂

**Comment by diamante0018** [comment]
Close because it's a won't fix

**Comment by LeRutY** [comment]
> Close because it's a won't fix

Bad answer, rip iw6x for people that want to level up with bots
