### ISSUE TITLE
Spectator not working for dedicated server

### ISSUE THREAD

**Issue by amrurikaj** [XLabsProject/iw6x-client#705]
Spectator not working for dedicated server. Cannot go anywhere and just static at the same place

**Comment by Dss0** [comment]
what is `scr_game_spectatetype` set to on the server? 0 is disabled, 1 is player only and 2 is free.

**Comment by diamante0018** [comment]
https://github.com/XLabsProject/IW6ServerConfigs/blob/master/iw6x/server.cfg#L77

**Comment by amrurikaj** [comment]
> what is `scr_game_spectatetype` set to on the server? 0 is disabled, 1 is player only and 2 is free.

this one i check its "2"

**Comment by amrurikaj** [comment]
> You should ask in iw6x support for issues like this.
> 
> GitHub issues are not for getting help setting up the client. Chances are if you control+f your issue in the discord server you would find the answer for your problem. You wouldn't be able to do this in GitHub.
> 
> 
> 
> You are not meant to open a GitHub issue with the purpose of getting help "faster"

nah!!i just want to help only.chill bro.just keep chill.scr_game_spectatetype this one i set to 2 already that is why i open this.

**Comment by diamante0018** [comment]
I don't consider myself your bro.
If you were aware you already set scr_game_spectatetype to 2 and therefore you opened this issue why didn't you mention it? That could have saved some time.

**Comment by amrurikaj** [comment]
> I don't consider myself your bro.
> 
> If you were aware you already set scr_game_spectatetype to 2 and therefore you opened this issue why didn't you mention it? That could have saved some time.

nevermind.i just forgot to mention the main issue.the scr_game_spectatetype

**Comment by diamante0018** [comment]
Are you using this exe from develop branch?
https://master.xlabs.dev/data-dev/iw6x/iw6x.exe

Something was recently changed on the develop branch that should force the game to use the dvars from the cfg. Also check again with this new exe the dvar is set to two. I'm gonna test this on my own in a bit.

**Comment by amrurikaj** [comment]
@diamante0018 nope.i took server file from the link provided at the iw6x for dedicated server forum and the iw6x client directly from main page

**Comment by diamante0018** [comment]
Okay. I will test with the latest exe from develop in a bit to see if the issue is there as well.
If you use the xlabs launcher you can get the develop exe by switching to the experimental update channel.

**Comment by amrurikaj** [comment]
@diamante0018 ok.thanks.sorry for the problem happened 👍

**Comment by diamante0018** [comment]
The dvar is set to 1 after the map rotates by a game script.
Now that GSC script support is in the client you should be able to fix that. Please come to the iw6x-modding channel if you need help with that (or use a lua script if you prefer those).
I'm gonna try to figure it out myself in the meantime as I still have to pinpoint which scripts modifies the value of this dvar.

As a workaround you can have a simple script in lua that does set the dvar to 2 every x second. See the scripting guide here
https://xlabs.dev/iw6x_scripting_documentation.
You can do this with gsc very easily.

**Comment by amrurikaj** [comment]
@diamante0018 tq very much.I will follow up the discord if have any problem.

**Comment by efinst0rm** [comment]
@amrurikaj this should be fixed fully with this commit

#805
