### ISSUE TITLE
Investigate high CPU usage on DS.

### ISSUE THREAD

**Issue by xerxes-at** [XLabsProject/iw6x-client#74]
Dedicated Servers will utilize a single CPU core at 100% no matter if a map is loaded or not.
Might be related to #67

**Comment by momo5502** [comment]
My dedi uses 2% of cpus resources. I can't reproduce this. Can you see if it's still valid? It might have been related to issue #76

**Comment by Dss0** [comment]
this is still valid, also the case for me. It pins a single thread of the cpu at 100% utilization even with no players on the server and without a map loaded.

**Comment by momo5502** [comment]
This is the same issue as #67 !
