### ISSUE TITLE
Gsc feature request

### ISSUE THREAD

**Issue by Divity** [XLabsProject/iw6x-client#746]
HTTPGET and Request features (specifically for sending in game events to discord webhooks)
Ex: https://github.com/fedddddd/t5-gsc-utils/blob/main/src/component/http.cpp

**Comment by diamante0018** [comment]
We don't add these features to our XLabs client because of the increased security risk it poses to allow GSC scripts to connect to the internet. We removed it on IW4x so there is no way this gets added here and the same goes for IO functions.

**Comment by Rackover** [comment]
Please use an external script (using python, shellscript, powershell, anything) for your web hooks :)  
You can then monitor for file changes for instance and fire your discord webhook from your python script whenever a file has changed

**Comment by Divity** [comment]
Probably won't go that route and will implement this for my server side myself. Was hoping it could hit be over all added. I much prefer this method compared to the alternatives.
