### ISSUE TITLE
Dedicated server takes up a player slot

### ISSUE THREAD

**Issue by OneFourOne** [XLabsProject/iw6x-client#75]
In the matches it just sits because it's not forced to pick a class, on a gamemode like safeguard it will force spawn in as a player.

**Comment by momo5502** [comment]
How did you notice? This should not happen as self registration is off

**Comment by OneFourOne** [comment]
I opened the scoreboard in tdm and saw that there was two players named "OneFourOne" (this was because of my players folder being in both directories which I then deleted, without it just spawns "Unknown Soldier") I then tested in safeguard which spawns the player in. I'm using the latest version of IW6x as well.

**Comment by momo5502** [comment]
@OneFourOne can you please verify if the issue is fixed?

**Comment by OneFourOne** [comment]
Issue has been fixed.

**Comment by OneFourOne** [comment]
Setting the gametype to war doesn't spawn a client in. Setting to another gametype seems to spawn in the dedi as a client.

**Comment by momo5502** [comment]
PartyHost_AddLocalPlayer is responsible for registering a local player. I killed that function. I can't see why the dedi still registers itself.
