### ISSUE TITLE
Fatal imagefile error

### ISSUE THREAD

**Issue by Burvye** [XLabsProject/iw6x-client#785]
Every time i try to launch iw6x multiplayer it loads for a bit then spits out an imagefile error
using the xlabs launcher it happens while loading mp characterroom heads
on the iw6x launcher it happens only half the time but in return it blocks me from playing on servers
![Annotation 2022-11-23 175400](https://user-images.githubusercontent.com/110496639/203659601-f759e963-5a6c-4153-8e48-b8e3c6f6a2b7.png)

**Comment by diamante0018** [comment]
Seek help in the xlabs discord.
I suggest in the meantime you follow our repair guidehttps://xlabs.dev/iw6x_repair.
Closing this as it's most likely not a client issue.
