### ISSUE TITLE
dump console commands?

### ISSUE THREAD

**Issue by Crugnok** [XLabsProject/iw6x-client#794]
hi, how do you dump all console commands? i tried commandDump and dvardump but nothing happens. i wan to see all the console commands but the console won't list them as it says there's too many to list.

**Comment by Crugnok** [comment]
so i take it's not implemented yet?

also how do you make console commands stick? i've put a bunch in autoexec.cfg but the game won't pick it up on launch, i have to keep executing it from the console once in-game. and after dying they are reset.

**Comment by diamante0018** [comment]
@Crugnok this is not the place to post queries about modding. You must first go through the xlabs discord server.
