### ISSUE TITLE
unknown hard error

### ISSUE THREAD

**Issue by Burvye** [XLabsProject/iw6x-client#796]
after using the fix displayed in this video: https://www.youtube.com/watch?v=oiNSpSYTmDA&t=1s
it worked for a bit, but then further customization came up with this error:
![image](https://user-images.githubusercontent.com/110496639/204167256-31bdda09-5320-49ac-961c-a0c40db4a683.png)

**Comment by diamante0018** [comment]
Trying out a fix on a random youtube video was not a good idea. We provide help for things like this on the xlabs discord server.
https://discord.gg/sKeVmR3
