### ISSUE TITLE
DXGI device removed

### ISSUE THREAD

**Issue by Burvye** [XLabsProject/iw6x-client#798]
more errors on specifically iw6x multiplayer rather than iw6x singleplayer or iw4x
![image](https://user-images.githubusercontent.com/110496639/204171315-77624498-9ba1-4442-a07b-a000e2231618.png)

**Comment by diamante0018** [comment]
Why do you have so many problems.
There is no saving you.
Also these issues you are opening are useless.
You are not welcome to post here anymore
