### ISSUE TITLE
Extinction Dedicated Server Disk Space Error

### ISSUE THREAD

**Issue by GAMECRIS** [XLabsProject/iw6x-client#802]
After some hours our Extinction servers will crash.

We already made a new install of the game on a different hard disk. Deleted the appdata files and used the official xlabs updater. Still the same issues.

We get sometimes this error spammt in the console:

* script runtime error 
in call to builtin function "distancesquared": Type undefined is not a vector    at function "filter_spawn_point_by_distance_from_player" in file "maps/mp/alien/_spawn_director.gsc"
    at function "passes_spawn_node_filter" in file "maps/mp/alien/_spawn_director.gsc"
    at function "find_random_spawn_node" in file "maps/mp/alien/_spawn_director.gsc"
    at function "_id_3273" in file "maps/mp/alien/_spawn_director.gsc"
    at function "_id_776C" in file "maps/mp/alien/_spawn_director.gsc"
    at function "_id_776F" in file "maps/mp/alien/_spawn_director.gsc"
    at function "_id_7848" in file "maps/mp/alien/_spawn_director.gsc"
    at function "_id_7856" in file "maps/mp/alien/_spawn_director.gsc"
    at function "_id_6627" in file "maps/mp/alien/_spawn_director.gsc"
    at function "_id_77A4" in file "maps/mp/alien/_spawn_director.gsc"
**
Error: EXE_DEMONWARE_DISCONNECT

Than the server crash with an error window that says disk space full 

And sometimes the server name of the console will disappear and then it says only "Iw6x dedicated server"

People can't join the servers anymore.

**Comment by diamante0018** [comment]
Disk space is full means that the game ran out of memory not actual disc space.
The script runime errors can be ignored.
Without a minidumps this issue is not useful at all.
Post the minidumps

**Comment by diamante0018** [comment]
Actually I will close this in 24 hours if you don't use the correct format:
https://github.com/XLabsProject/iw6x-client/blob/develop/.github/ISSUE_TEMPLATE/get-help.md
We added this document to help users avoid creating useless posts like this one.

**Comment by GAMECRIS** [comment]
unfortunately no minidump is created
I'm sorry if it doesn't fit the way I posted it

**Comment by GAMECRIS** [comment]
> Disk space is full means that the game ran out of memory not actual disc space. The script runime errors can be ignored. Without a minidumps this issue is not useful at all. Post the minidumps

but idk why we have enough memory

**Comment by diamante0018** [comment]
Too be honest there might be a memory leak.
If it doesn't crash with a memory dump there isn't basically anything we can do apart from blindly guessing where it might come from

**Comment by GAMECRIS** [comment]
[games_nig.log](https://github.com/XLabsProject/iw6x-client/files/10107376/games_nig.log)

**Comment by GAMECRIS** [comment]
thats the only what i have

**Comment by GAMECRIS** [comment]
Unfortunately the problem persists and we still don't have a specific error log or anything
