### ISSUE TITLE
Move publisher files outside of compiled application

### ISSUE THREAD

**Issue by WantedDV** [XLabsProject/iw6x-client#838]
Is it possible to move the dw publisher files from `src/client/resources/dw` to the `data` folder so they are more accessible? 

**What problem will this solve?**
This would allow playlists to be modified without having to recompile the application. As seen in this fork [iw6x-joseupp](https://github.com/XLabsProject/iw6x-client/commit/d4e501df5265dc288decee8e76642d86902d48bc) simply modifying the playlist allows for matchmaking against bots with a working progression system. I think this would be a nice feature for iw6x and s1x (and possibly H1 but I have not tested bots on v1.15).

**What other alternatives have you already considered?**
The fork mentioned above works fine for people really wanting to level up against bots, however it is really not a good idea for people to be running forks or older versions of the game; they should use modified playlists, not modified executables.

**Anything else we should know?**
Ayria used an open filesystem for publisher files.

**Comment by diamante0018** [comment]
Feel free to make a pull request

**Comment by diamante0018** [comment]
Yeah doesn't seem to hard. If I have time I will make it in the next following days/weeks. Kind of low priority right now as there is quite a few things I have to do first
