### ISSUE TITLE
Unfortunately the problem persists and we still don't have a specific error log or anything

### ISSUE THREAD

**Issue by GAMECRIS** [XLabsProject/iw6x-client#869]
Unfortunately the problem persists and we still don't have a specific error log or anything

_Originally posted by @GAMECRIS in https://github.com/XLabsProject/iw6x-client/issues/802#issuecomment-1427119498_

**Comment by mjkzy** [comment]
for starters, in the original issue, you were told that script runtime errors can be ignored. even though this is unrelated to the memory leak possibly, this is false and that means your mod may be possibly broken. however, i don't think that will cause a memory leak.

**Comment by GAMECRIS** [comment]
Yeah i know that the runtime error can be ignored but I have still the problem that the console say iw6x dedicated server and the server stop working no error nothing or disk space error this happend every time the server is to often restarted or after a few hours.
We have no mods install only the log script  we tested already without the script still the same problem.

**Comment by diamante0018** [comment]
`If it doesn't crash with a memory dump there isn't basically anything we can do apart from blindly guessing...`
What was said in that post still holds true, from the script runtime errors and how issues like this cannot be tackled with the sparse info you are giving us.

Are you going to upload a crash dump? They can be found in the iw6x game folder in the minidump folder.
Alternatively, they might also be in the crashdumps folder located in local app data.

**Comment by diamante0018** [comment]
Also, I would like to know if you have updated IW6x since the last time you wrote here on GitHub, if so prove it by taking a screenshot of the game date displayed when the server starts up.
Example:
```
------- Game Initialization -------
gamename: IW6
gamedate: Month Day Year
Logging to disk: 'logs/games_mp.log'.
```

**Comment by GAMECRIS** [comment]
------- Game Initialization -------
gamename: IW6
gamedate: Feb 13 2023
Logging to disk: 'logs/games_aw.log'.

there are no minidumps/crashdumps if you want you can add me on Discord and we can take a look together on my files GAMECHRIS#4577

**Comment by diamante0018** [comment]
Sorry, after analyzing all the minidumps there is nothing I can tell.
