### ISSUE TITLE
DirectX encountered an unrecoverable error

### ISSUE THREAD

**Issue by GhostMacTavish** [XLabsProject/iw6x-client#898]
I click on Multiplayer or Singleplayer and it says: "DirectX encountered an unrecoverable error", I have DirectX downloaded nut cant play IW6x.

**Comment by diamante0018** [comment]
Hello, please familiarise yourself with this document that should have appeared in front of you when creating a new issue.
[get-help](https://github.com/XLabsProject/iw6x-client/blob/develop/.github/ISSUE_TEMPLATE/get-help.md) 
The TL;DR version is Direct X issues are not a client issue, they are a support issue that should be dealt in the XLabs Discord. Join it here: [invite link](https://discord.gg/sKeVmR3)
