### ISSUE TITLE
Unable to change map in private match

### ISSUE THREAD

**Issue by JustNato** [XLabsProject/iw6x-client#901]
As the title says whenever I change map while in private match it will not load into the level. It changes the background, and starts loading the level but as it is about to start it just hangs in the loading screen. I have included a YouTube video below showing the issue. I load into Prison Break just fine, but when I use the console command to change map it causes it to not load the level properly. It just stays on the loading screen after that mini refresh near the end. I am on the latest version of the XLabs launcher, I have tried both experimental and stable and both cause this issue. When I am on my dedicated server this issue doesn't happen when I change map.

https://www.youtube.com/watch?v=02zIauNJv14

**Comment by diamante0018** [comment]
Hi, these commands are for dedicated use only. Do not use them on the client.

**Comment by JustNato** [comment]
Okay my bad sorry for that.
