### ISSUE TITLE
Verify the game binary versions

### ISSUE THREAD

**Issue by momo5502** [XLabsProject/iw6x-client#92]
Something like this, maybe simpler: https://github.com/XLabsProject/iw4x-client/blob/develop/src/Main.cpp#L58

**Comment by adamokke** [comment]
will this infect my pc

**Comment by sortileges** [comment]
@adamokke Not sure how a project that's 100% opensourced would "infect your PC". You can look at the source code by yourself if you so desire.

**Comment by momo5502** [comment]
Comment was deleted as it was dumb af and unrelated to the issue

**Comment by GEEKiDoS** [comment]
Maybe just include the binary in the resource similar to you did in the open-iw5?

**Comment by momo5502** [comment]
Nah, that would be copyright infringement. For now we are not distributed any copyrighted files, and I want it to stay that way, tbh
