### ISSUE TITLE
Discord integration displays own hostname, not the remote one

### ISSUE THREAD

**Issue by momo5502** [XLabsProject/iw6x-client#94]
Discord integration shows your own sv_hostname not the sv_hostname of the dedi you are connected to.
In iw4x we were able to read the hosts name here: https://github.com/XLabsProject/iw4x-client/blob/develop/src/Components/Modules/ServerInfo.cpp#L93
0x7ED3F8 was the address at which the IW4 stored the hostname. Maybe iw6 has the same concept.

**Comment by fischl-chan** [comment]
pog
