### ISSUE TITLE
Trying to change my clan tag on iw6x via console - not working

### ISSUE THREAD

**Issue by badjuice** [XLabsProject/iw6x-client#945]
**What are you trying to do?**
Trying to change my clan tag on iw6x

**What problem are you having?**
The console command should work in order to change my clan tag but it isn't

**What have you tried so far?**
The command I'm using on the console to change the clantag is clanName as it is [here](https://xlabs.dev/console_commands) on the list of console commands. I tried it ingame and on the menu. Nothing happens. And the command does not show in the console.

**What version of IW6x are you using?**
Latest one so far

**Anything else we should know?**
If this is not working, is there an alternative method to change the clan tag? I'd appreciate feedback.

**Comment by diamante0018** [comment]
I do not believe we have a clantag on this game
A suggested workaround is to type `/name [My Tag]My name` in the console.
Unfortunately we are not planning on working on any new features for this client.
