### ISSUE TITLE
Adding Extinction's Intel Menu

### ISSUE THREAD

**Issue by ClashTown** [XLabsProject/iw6x-client#957]
Right now the option for checking your Intel in extinction's main menu is not available.

I hope it will be added.

**Comment by diamante0018** [comment]
Not planned

**Comment by Rackover** [comment]
since this is an open source project, maybe we could keep that issue open in "waiting for community contribution" in case someone wants to tackle it one day?

closing the issue just means someone will eventually recreate it, unaware this one exists.
